// Copyright 2021 Samsung Electronics Co., Ltd. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// ignore_for_file: type=lint, unused_element, unused_field

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
import 'dart:ffi' as ffi;

/// @deprecated Deprecated since 8.0.
/// @brief Enumeration for Geofence manager of error code.
/// @since_tizen 2.4
abstract class geofence_manager_error_e {
  /// < Success
  static const int GEOFENCE_MANAGER_ERROR_NONE = 0;

  /// < Out of memory
  static const int GEOFENCE_MANAGER_ERROR_OUT_OF_MEMORY = -12;

  /// < Invalid parameter
  static const int GEOFENCE_MANAGER_ERROR_INVALID_PARAMETER = -22;

  /// < Permission denied
  static const int GEOFENCE_MANAGER_ERROR_PERMISSION_DENIED = -13;

  /// < Not supported
  static const int GEOFENCE_MANAGER_ERROR_NOT_SUPPORTED = -1073741822;

  /// < Geofence Manager is not initialized
  static const int GEOFENCE_MANAGER_ERROR_NOT_INITIALIZED = -46202879;

  /// < Invalid geofence ID
  static const int GEOFENCE_MANAGER_ERROR_INVALID_ID = -46202878;

  /// < Exception occurs
  static const int GEOFENCE_MANAGER_ERROR_EXCEPTION = -46202877;

  /// < Geofencing is already started
  static const int GEOFENCE_MANAGER_ERROR_ALREADY_STARTED = -46202876;

  /// < Too many geofence
  static const int GEOFENCE_MANAGER_ERROR_TOO_MANY_GEOFENCE = -46202875;

  /// < Error in GPS, Wi-Fi, or BT
  static const int GEOFENCE_MANAGER_ERROR_IPC = -46202874;

  /// < DB error in the server side
  static const int GEOFENCE_MANAGER_ERROR_DATABASE = -46202873;

  /// < Access to specified place is denied
  static const int GEOFENCE_MANAGER_ERROR_PLACE_ACCESS_DENIED = -46202872;

  /// < Access to specified geofence is denied
  static const int GEOFENCE_MANAGER_ERROR_GEOFENCE_ACCESS_DENIED = -46202871;
}

/// @deprecated Deprecated since 8.0.
/// @brief Enumeration for the state of geofence manager.
/// @since_tizen 2.4
abstract class geofence_state_e {
  /// < Uncertain state of geofence
  static const int GEOFENCE_STATE_UNCERTAIN = 0;

  /// < Geofence In state
  static const int GEOFENCE_STATE_IN = 1;

  /// < Geofence Out state
  static const int GEOFENCE_STATE_OUT = 2;
}

/// @deprecated Deprecated since 8.0.
/// @brief Enumeration for the state of proximity.
/// @since_tizen 3.0
abstract class geofence_proximity_state_e {
  /// < Uncertain state of proximity
  static const int GEOFENCE_PROXIMITY_STATE_UNCERTAIN = 0;

  /// < Far state of proximity
  static const int GEOFENCE_PROXIMITY_STATE_FAR = 1;

  /// < Near state of proximity
  static const int GEOFENCE_PROXIMITY_STATE_NEAR = 2;

  /// < Immediate state of proximity
  static const int GEOFENCE_PROXIMITY_STATE_IMMEDIATE = 3;
}

/// @deprecated Deprecated since 8.0.
/// @brief Enumeration for the provider of proximity.
/// @since_tizen 3.0
abstract class geofence_proximity_provider_e {
  /// < Proximity is specified by geospatial coordinate
  static const int GEOFENCE_PROXIMITY_PROVIDER_LOCATION = 0;

  /// < Proximity is specified by Wi-Fi access point
  static const int GEOFENCE_PROXIMITY_PROVIDER_WIFI = 1;

  /// < Proximity is specified by Bluetooth device
  static const int GEOFENCE_PROXIMITY_PROVIDER_BLUETOOTH = 2;

  /// < Proximity is specified by Bluetooth low energy device
  static const int GEOFENCE_PROXIMITY_PROVIDER_BLE = 3;

  /// < Proximity is specified by Sensor
  static const int GEOFENCE_PROXIMITY_PROVIDER_SENSOR = 4;
}

/// @deprecated Deprecated since 8.0.
/// @brief Enumeration for geofence type.
/// @since_tizen 2.4
abstract class geofence_type_e {
  /// < Geofence is specified by geospatial coordinate
  static const int GEOFENCE_TYPE_GEOPOINT = 1;

  /// < Geofence is specified by Wi-Fi access point
  static const int GEOFENCE_TYPE_WIFI = 2;

  /// < Geofence is specified by Bluetooth device
  static const int GEOFENCE_TYPE_BT = 3;
}

/// @deprecated Deprecated since 8.0.
/// @brief Enumeration for geofence management events.
/// @since_tizen 2.4
abstract class geofence_manage_e {
  /// < Geofence is added
  static const int GEOFENCE_MANAGE_FENCE_ADDED = 0;

  /// < Geofence is removed
  static const int GEOFENCE_MANAGE_FENCE_REMOVED = 1;

  /// < Geofencing is started
  static const int GEOFENCE_MANAGE_FENCE_STARTED = 2;

  /// < Geofencing is stopped
  static const int GEOFENCE_MANAGE_FENCE_STOPPED = 3;

  /// < Place is added
  static const int GEOFENCE_MANAGE_PLACE_ADDED = 16;

  /// < Place is removed
  static const int GEOFENCE_MANAGE_PLACE_REMOVED = 17;

  /// < Place is updated
  static const int GEOFENCE_MANAGE_PLACE_UPDATED = 18;

  /// < Setting for geofencing is enabled
  static const int GEOFENCE_MANAGE_SETTING_ENABLED = 32;

  /// < Setting for geofencing is disabled
  static const int GEOFENCE_MANAGE_SETTING_DISABLED = 33;
}

final class geofence_manager_s extends ffi.Opaque {}

final class geofence_s extends ffi.Opaque {}

final class geofence_status_s extends ffi.Opaque {}
