preamble: |
  // Copyright 2021 Samsung Electronics Co., Ltd. All rights reserved.
  // Use of this source code is governed by a BSD-style license that can be
  // found in the LICENSE file.
  // ignore_for_file: type=lint, unused_element, unused_field

name: Tizen65NotificationEx
description: Dart bindings for Tizen notification-ex APIs.
output: ../../lib/src/bindings/6.5/generated_bindings_notification_ex.dart
llvm-path:
- /usr/lib/llvm-12
headers:
  entry-points:
  - entrypoints-notification-ex.h
  include-directives:
  - '**/notification_ex.h'
  - '**/notification_ex_app_control_action.h'
  - '**/notification_ex_button.h'
  - '**/notification_ex_chat_message.h'
  - '**/notification_ex_checkbox.h'
  - '**/notification_ex_entry.h'
  - '**/notification_ex_error.h'
  - '**/notification_ex_event_info.h'
  - '**/notification_ex_group.h'
  - '**/notification_ex_image.h'
  - '**/notification_ex_input_selector.h'
  - '**/notification_ex_progress.h'
  - '**/notification_ex_manager.h'
  - '**/notification_ex_reporter.h'
  - '**/notification_ex_text.h'
  - '**/notification_ex_time.h'
  - '**/notification_ex_visibility_action.h'
  - '**/notification_ex_multi_language.h'
  - '**/notification_ex_item.h'
compiler-opts:
- -m32
- -Wno-incomplete-setjmp-declaration
- -I./rootstraps/6.5/usr/include/
- -I./rootstraps/6.5/usr/include/notification-ex/api/
- -I./rootstraps/6.5/usr/include/appfw/
enums:
  rename:
    _+(.*): $1
