preamble: |
  // Copyright 2021 Samsung Electronics Co., Ltd. All rights reserved.
  // Use of this source code is governed by a BSD-style license that can be
  // found in the LICENSE file.
  // ignore_for_file: type=lint, unused_element, unused_field

name: Tizen65CapiUiAutofillService
description: Dart bindings for Tizen capi-ui-autofill-service APIs.
output: ../../lib/src/bindings/6.5/generated_bindings_capi_ui_autofill_service.dart
llvm-path:
- /usr/lib/llvm-12
headers:
  entry-points:
  - entrypoints-capi-ui-autofill-service.h
  include-directives:
  - '**/autofill_service.h'
compiler-opts:
- -m32
- -Wno-incomplete-setjmp-declaration
- -I./rootstraps/6.5/usr/include/
- -I./rootstraps/6.5/usr/include/autofill/
enums:
  rename:
    _+(.*): $1
