/// {@category 9.0/tizen}
library tizen_interop_9_0.tts_setting;

// Copyright 2021 Samsung Electronics Co., Ltd. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// ignore_for_file: type=lint, unused_element, unused_field

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
import 'dart:ffi' as ffi;

/// Dart bindings for Tizen tts_setting APIs.
/// {@category 9.0/tizen}
class Tizen90TtsSetting {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  Tizen90TtsSetting(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  Tizen90TtsSetting.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  /// Initialize TTS setting.
  ///
  /// **Remarks:**
  /// - If the function succeeds, `tts` setting must be released with tts_setting_finalize().
  ///
  /// **Returns:**
  /// - 0 on success, otherwise a negative error value.
  ///
  /// **Return values:**
  /// - `TTS_SETTING_ERROR_NONE`: Success.
  /// - `TTS_SETTING_ERROR_INVALID_STATE`: TTS setting has Already been initialized.
  /// - `TTS_SETTING_ERROR_OPERATION_FAILED`: Operation failure.
  /// - `TTS_SETTING_ERROR_NOT_SUPPORTED`: TTS NOT supported
  ///
  /// **See also:**
  /// - `tts_setting_finalize()`
  int tts_setting_initialize() {
    return _tts_setting_initialize();
  }

  late final _tts_setting_initializePtr =
      _lookup<ffi.NativeFunction<ffi.Int Function()>>('tts_setting_initialize');
  late final _tts_setting_initialize =
      _tts_setting_initializePtr.asFunction<int Function()>();

  /// finalize TTS setting.
  ///
  /// **Returns:**
  /// - 0 on success, otherwise a negative error value.
  ///
  /// **Return values:**
  /// - `TTS_SETTING_ERROR_NONE`: Success.
  /// - `TTS_SETTING_ERROR_INVALID_STATE`: Not initialized.
  /// - `TTS_SETTING_ERROR_OPERATION_FAILED`: Operation failure.
  /// - `TTS_SETTING_ERROR_NOT_SUPPORTED`: TTS NOT supported
  ///
  /// **See also:**
  /// - `tts_setting_initialize()`
  int tts_setting_finalize() {
    return _tts_setting_finalize();
  }

  late final _tts_setting_finalizePtr =
      _lookup<ffi.NativeFunction<ffi.Int Function()>>('tts_setting_finalize');
  late final _tts_setting_finalize =
      _tts_setting_finalizePtr.asFunction<int Function()>();

  /// Retrieve supported engine informations using callback function.
  ///
  /// **Parameters:**
  /// - `callback` (in): Callback function
  /// - `user_data` (in): User data to be passed to the callback function
  ///
  /// **Returns:**
  /// - 0 on success, otherwise a negative error value.
  ///
  /// **Return values:**
  /// - `TTS_SETTING_ERROR_NONE`: Success.
  /// - `TTS_SETTING_ERROR_INVALID_PARAMETER`: Invalid parameter.
  /// - `TTS_SETTING_ERROR_INVALID_STATE`: Not initialized.
  /// - `TTS_SETTING_ERROR_NOT_SUPPORTED`: TTS NOT supported
  ///
  /// **Postconditions:**
  /// - This function invokes tts_setting_supported_engine_cb() repeatedly for getting engine information.
  ///
  /// **See also:**
  /// - `tts_setting_supported_engine_cb()`
  int tts_setting_foreach_supported_engines(
    tts_setting_supported_engine_cb callback,
    ffi.Pointer<ffi.Void> user_data,
  ) {
    return _tts_setting_foreach_supported_engines(
      callback,
      user_data,
    );
  }

  late final _tts_setting_foreach_supported_enginesPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(tts_setting_supported_engine_cb,
              ffi.Pointer<ffi.Void>)>>('tts_setting_foreach_supported_engines');
  late final _tts_setting_foreach_supported_engines =
      _tts_setting_foreach_supported_enginesPtr.asFunction<
          int Function(
              tts_setting_supported_engine_cb, ffi.Pointer<ffi.Void>)>();

  /// Get current engine id.
  ///
  /// **Remarks:**
  /// - If the function is success, `engine_id` must be released with free() by you.
  ///
  /// **Parameters:**
  /// - `engine_id` (out): Engine id
  ///
  /// **Returns:**
  /// - 0 on success, otherwise a negative error value.
  ///
  /// **Return values:**
  /// - `TTS_SETTING_ERROR_NONE`: Success.
  /// - `TTS_SETTING_ERROR_OUT_OF_MEMORY`: Out of memory.
  /// - `TTS_SETTING_ERROR_INVALID_PARAMETER`: Invalid parameter.
  /// - `TTS_SETTING_ERROR_INVALID_STATE`: Not initialized.
  /// - `TTS_SETTING_ERROR_OPERATION_FAILED`: Operation failure.
  /// - `TTS_SETTING_ERROR_NOT_SUPPORTED`: TTS NOT supported
  ///
  /// **See also:**
  /// - `tts_setting_set_engine()`
  int tts_setting_get_engine(
    ffi.Pointer<ffi.Pointer<ffi.Char>> engine_id,
  ) {
    return _tts_setting_get_engine(
      engine_id,
    );
  }

  late final _tts_setting_get_enginePtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(
              ffi.Pointer<ffi.Pointer<ffi.Char>>)>>('tts_setting_get_engine');
  late final _tts_setting_get_engine = _tts_setting_get_enginePtr
      .asFunction<int Function(ffi.Pointer<ffi.Pointer<ffi.Char>>)>();

  /// Set current engine id.
  ///
  /// **Parameters:**
  /// - `engine_id` (in): Engine id
  ///
  /// **Returns:**
  /// - 0 on success, otherwise a negative error value.
  ///
  /// **Return values:**
  /// - `TTS_SETTING_ERROR_NONE`: Success.
  /// - `TTS_SETTING_ERROR_INVALID_PARAMETER`: Invalid parameter.
  /// - `TTS_SETTING_ERROR_INVALID_STATE`: Not initialized.
  /// - `TTS_SETTING_ERROR_OPERATION_FAILED`: Operation failure.
  /// - `TTS_SETTING_ERROR_NOT_SUPPORTED`: TTS NOT supported
  ///
  /// **See also:**
  /// - `tts_setting_get_engine()`
  int tts_setting_set_engine(
    ffi.Pointer<ffi.Char> engine_id,
  ) {
    return _tts_setting_set_engine(
      engine_id,
    );
  }

  late final _tts_setting_set_enginePtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<ffi.Char>)>>(
          'tts_setting_set_engine');
  late final _tts_setting_set_engine = _tts_setting_set_enginePtr
      .asFunction<int Function(ffi.Pointer<ffi.Char>)>();

  /// Get supported voices of current engine.
  ///
  /// **Parameters:**
  /// - `callback` (in): Callback function
  /// - `user_data` (in): User data to be passed to the callback function
  ///
  /// **Returns:**
  /// - 0 on success, otherwise a negative error value.
  ///
  /// **Return values:**
  /// - `TTS_SETTING_ERROR_NONE`: Success.
  /// - `TTS_SETTING_ERROR_INVALID_PARAMETER`: Invalid parameter.
  /// - `TTS_SETTING_ERROR_INVALID_STATE`: Not initialized.
  /// - `TTS_SETTING_ERROR_OPERATION_FAILED`: Operation failure.
  /// - `TTS_SETTING_ERROR_NOT_SUPPORTED`: TTS NOT supported
  ///
  /// **Postconditions:**
  /// - This function invokes tts_setting_supported_voice_cb() repeatedly for getting supported voices.
  ///
  /// **See also:**
  /// - `tts_setting_supported_voice_cb()`
  int tts_setting_foreach_supported_voices(
    tts_setting_supported_voice_cb callback,
    ffi.Pointer<ffi.Void> user_data,
  ) {
    return _tts_setting_foreach_supported_voices(
      callback,
      user_data,
    );
  }

  late final _tts_setting_foreach_supported_voicesPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(tts_setting_supported_voice_cb,
              ffi.Pointer<ffi.Void>)>>('tts_setting_foreach_supported_voices');
  late final _tts_setting_foreach_supported_voices =
      _tts_setting_foreach_supported_voicesPtr.asFunction<
          int Function(
              tts_setting_supported_voice_cb, ffi.Pointer<ffi.Void>)>();

  /// Get a default voice of current engine.
  ///
  /// **Remarks:**
  /// - If the function is success, `language` must be released with free() by you.
  ///
  /// **Parameters:**
  /// - `language` (out): Default language
  /// - `voice_type` (out): Default voice type
  ///
  /// **Returns:**
  /// - 0 on success, otherwise a negative error value.
  ///
  /// **Return values:**
  /// - `TTS_SETTING_ERROR_NONE`: Success.
  /// - `TTS_SETTING_ERROR_OUT_OF_MEMORY`: Out of memory.
  /// - `TTS_SETTING_ERROR_INVALID_PARAMETER`: Invalid parameter.
  /// - `TTS_SETTING_ERROR_INVALID_STATE`: Not initialized.
  /// - `TTS_SETTING_ERROR_OPERATION_FAILED`: Operation failure.
  /// - `TTS_SETTING_ERROR_NOT_SUPPORTED`: TTS NOT supported
  ///
  /// **See also:**
  /// - `tts_setting_set_voice()`
  int tts_setting_get_voice(
    ffi.Pointer<ffi.Pointer<ffi.Char>> language,
    ffi.Pointer<ffi.Int> voice_type,
  ) {
    return _tts_setting_get_voice(
      language,
      voice_type,
    );
  }

  late final _tts_setting_get_voicePtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<ffi.Pointer<ffi.Char>>,
              ffi.Pointer<ffi.Int>)>>('tts_setting_get_voice');
  late final _tts_setting_get_voice = _tts_setting_get_voicePtr.asFunction<
      int Function(ffi.Pointer<ffi.Pointer<ffi.Char>>, ffi.Pointer<ffi.Int>)>();

  /// Set a default voice of current engine.
  ///
  /// **Parameters:**
  /// - `language` (in): Default language
  /// - `voice_type` (in): Default voice type
  ///
  /// **Returns:**
  /// - 0 on success, otherwise a negative error value.
  ///
  /// **Return values:**
  /// - `TTS_SETTING_ERROR_NONE`: Success.
  /// - `TTS_SETTING_ERROR_INVALID_PARAMETER`: Invalid parameter.
  /// - `TTS_SETTING_ERROR_INVALID_STATE`: Not initialized.
  /// - `TTS_SETTING_ERROR_INVALID_VOICE`: Invalid voice.
  /// - `TTS_SETTING_ERROR_OPERATION_FAILED`: Operation failure.
  /// - `TTS_SETTING_ERROR_NOT_SUPPORTED`: TTS NOT supported
  ///
  /// **See also:**
  /// - `tts_setting_get_voice()`
  int tts_setting_set_voice(
    ffi.Pointer<ffi.Char> language,
    int voice_type,
  ) {
    return _tts_setting_set_voice(
      language,
      voice_type,
    );
  }

  late final _tts_setting_set_voicePtr = _lookup<
          ffi.NativeFunction<ffi.Int Function(ffi.Pointer<ffi.Char>, ffi.Int)>>(
      'tts_setting_set_voice');
  late final _tts_setting_set_voice = _tts_setting_set_voicePtr
      .asFunction<int Function(ffi.Pointer<ffi.Char>, int)>();

  /// Get a automatic option of voice.
  ///
  /// **Parameters:**
  /// - `value` (out): Automatic option
  ///
  /// **Returns:**
  /// - 0 on success, otherwise a negative error value.
  ///
  /// **Return values:**
  /// - `TTS_SETTING_ERROR_NONE`: Success.
  /// - `TTS_SETTING_ERROR_INVALID_PARAMETER`: Invalid parameter.
  /// - `TTS_SETTING_ERROR_INVALID_STATE`: Not initialized.
  /// - `TTS_SETTING_ERROR_OPERATION_FAILED`: Operation failure.
  /// - `TTS_SETTING_ERROR_NOT_SUPPORTED`: TTS NOT supported
  ///
  /// **See also:**
  /// - `tts_setting_set_auto_voice()`
  int tts_setting_get_auto_voice(
    ffi.Pointer<ffi.Bool> value,
  ) {
    return _tts_setting_get_auto_voice(
      value,
    );
  }

  late final _tts_setting_get_auto_voicePtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<ffi.Bool>)>>(
          'tts_setting_get_auto_voice');
  late final _tts_setting_get_auto_voice = _tts_setting_get_auto_voicePtr
      .asFunction<int Function(ffi.Pointer<ffi.Bool>)>();

  /// Set a automatic option of voice.
  ///
  /// **Parameters:**
  /// - `value` (in): Automatic option
  ///
  /// **Returns:**
  /// - 0 on success, otherwise a negative error value.
  ///
  /// **Return values:**
  /// - `TTS_SETTING_ERROR_NONE`: Success.
  /// - `TTS_SETTING_ERROR_INVALID_PARAMETER`: Invalid parameter.
  /// - `TTS_SETTING_ERROR_INVALID_STATE`: Not initialized.
  /// - `TTS_SETTING_ERROR_OPERATION_FAILED`: Operation failure.
  /// - `TTS_SETTING_ERROR_NOT_SUPPORTED`: TTS NOT supported
  ///
  /// **See also:**
  /// - `tts_setting_get_auto_voice()`
  int tts_setting_set_auto_voice(
    bool value,
  ) {
    return _tts_setting_set_auto_voice(
      value,
    );
  }

  late final _tts_setting_set_auto_voicePtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Bool)>>(
          'tts_setting_set_auto_voice');
  late final _tts_setting_set_auto_voice =
      _tts_setting_set_auto_voicePtr.asFunction<int Function(bool)>();

  /// Gets the speed range.
  ///
  /// **Parameters:**
  /// - `min` (out): The minimum speed value
  /// - `normal` (out): The normal speed value
  /// - `max` (out): The maximum speed value
  ///
  /// **Returns:**
  /// - 0 on success, otherwise a negative error value
  ///
  /// **Return values:**
  /// - `TTS_SETTING_ERROR_NONE`: Success.
  /// - `TTS_SETTING_ERROR_INVALID_PARAMETER`: Invalid parameter.
  /// - `TTS_SETTING_ERROR_INVALID_STATE`: Not initialized.
  /// - `TTS_SETTING_ERROR_NOT_SUPPORTED`: TTS NOT supported
  ///
  /// **See also:**
  /// - `tts_setting_get_speed()`
  /// - `tts_setting_set_speed()`
  int tts_setting_get_speed_range(
    ffi.Pointer<ffi.Int> min,
    ffi.Pointer<ffi.Int> normal,
    ffi.Pointer<ffi.Int> max,
  ) {
    return _tts_setting_get_speed_range(
      min,
      normal,
      max,
    );
  }

  late final _tts_setting_get_speed_rangePtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<ffi.Int>, ffi.Pointer<ffi.Int>,
              ffi.Pointer<ffi.Int>)>>('tts_setting_get_speed_range');
  late final _tts_setting_get_speed_range =
      _tts_setting_get_speed_rangePtr.asFunction<
          int Function(ffi.Pointer<ffi.Int>, ffi.Pointer<ffi.Int>,
              ffi.Pointer<ffi.Int>)>();

  /// Get default speed.
  ///
  /// **Parameters:**
  /// - `speed` (out): Default voice speed
  ///
  /// **Returns:**
  /// - 0 on success, otherwise a negative error value.
  ///
  /// **Return values:**
  /// - `TTS_SETTING_ERROR_NONE`: Success.
  /// - `TTS_SETTING_ERROR_INVALID_PARAMETER`: Invalid parameter.
  /// - `TTS_SETTING_ERROR_INVALID_STATE`: Not initialized.
  /// - `TTS_SETTING_ERROR_OPERATION_FAILED`: Operation failure.
  /// - `TTS_SETTING_ERROR_NOT_SUPPORTED`: TTS NOT supported
  ///
  /// **See also:**
  /// - `tts_setting_get_speed_range()`
  /// - `tts_setting_set_speed()`
  int tts_setting_get_speed(
    ffi.Pointer<ffi.Int> speed,
  ) {
    return _tts_setting_get_speed(
      speed,
    );
  }

  late final _tts_setting_get_speedPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<ffi.Int>)>>(
          'tts_setting_get_speed');
  late final _tts_setting_get_speed = _tts_setting_get_speedPtr
      .asFunction<int Function(ffi.Pointer<ffi.Int>)>();

  /// Set default speed.
  ///
  /// **Parameters:**
  /// - `speed` (in): Default voice speed
  ///
  /// **Returns:**
  /// - 0 on success, otherwise a negative error value.
  ///
  /// **Return values:**
  /// - `TTS_SETTING_ERROR_NONE`: Success.
  /// - `TTS_SETTING_ERROR_INVALID_PARAMETER`: Invalid parameter.
  /// - `TTS_SETTING_ERROR_INVALID_STATE`: Not initialized.
  /// - `TTS_SETTING_ERROR_OPERATION_FAILED`: Operation failure.
  /// - `TTS_SETTING_ERROR_NOT_SUPPORTED`: TTS NOT supported
  ///
  /// **See also:**
  /// - `tts_setting_get_speed_range()`
  /// - `tts_setting_get_speed()`
  int tts_setting_set_speed(
    int speed,
  ) {
    return _tts_setting_set_speed(
      speed,
    );
  }

  late final _tts_setting_set_speedPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Int)>>(
          'tts_setting_set_speed');
  late final _tts_setting_set_speed =
      _tts_setting_set_speedPtr.asFunction<int Function(int)>();

  /// Gets the pitch range.
  ///
  /// **Parameters:**
  /// - `min` (out): The minimum pitch value
  /// - `normal` (out): The normal pitch value
  /// - `max` (out): The maximum pitch value
  ///
  /// **Returns:**
  /// - 0 on success, otherwise a negative error value
  ///
  /// **Return values:**
  /// - `TTS_SETTING_ERROR_NONE`: Success.
  /// - `TTS_SETTING_ERROR_INVALID_PARAMETER`: Invalid parameter.
  /// - `TTS_SETTING_ERROR_INVALID_STATE`: Not initialized.
  /// - `TTS_SETTING_ERROR_NOT_SUPPORTED`: TTS NOT supported
  ///
  /// **See also:**
  /// - `tts_setting_get_pitch()`
  /// - `tts_setting_set_pitch()`
  int tts_setting_get_pitch_range(
    ffi.Pointer<ffi.Int> min,
    ffi.Pointer<ffi.Int> normal,
    ffi.Pointer<ffi.Int> max,
  ) {
    return _tts_setting_get_pitch_range(
      min,
      normal,
      max,
    );
  }

  late final _tts_setting_get_pitch_rangePtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<ffi.Int>, ffi.Pointer<ffi.Int>,
              ffi.Pointer<ffi.Int>)>>('tts_setting_get_pitch_range');
  late final _tts_setting_get_pitch_range =
      _tts_setting_get_pitch_rangePtr.asFunction<
          int Function(ffi.Pointer<ffi.Int>, ffi.Pointer<ffi.Int>,
              ffi.Pointer<ffi.Int>)>();

  /// Set a default pitch.
  ///
  /// **Parameters:**
  /// - `pitch` (out): Default voice pitch
  ///
  /// **Returns:**
  /// - 0 on success, otherwise a negative error value.
  ///
  /// **Return values:**
  /// - `TTS_SETTING_ERROR_NONE`: Success.
  /// - `TTS_SETTING_ERROR_INVALID_PARAMETER`: Invalid parameter.
  /// - `TTS_SETTING_ERROR_INVALID_STATE`: Not initialized.
  /// - `TTS_SETTING_ERROR_OPERATION_FAILED`: Operation failure.
  /// - `TTS_SETTING_ERROR_NOT_SUPPORTED_FEATURE`: Not supported feature.
  /// - `TTS_SETTING_ERROR_NOT_SUPPORTED`: TTS NOT supported
  ///
  /// **See also:**
  /// - `tts_setting_get_pitch_range()`
  /// - `tts_setting_set_pitch()`
  int tts_setting_get_pitch(
    ffi.Pointer<ffi.Int> pitch,
  ) {
    return _tts_setting_get_pitch(
      pitch,
    );
  }

  late final _tts_setting_get_pitchPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<ffi.Int>)>>(
          'tts_setting_get_pitch');
  late final _tts_setting_get_pitch = _tts_setting_get_pitchPtr
      .asFunction<int Function(ffi.Pointer<ffi.Int>)>();

  /// Set a default pitch.
  ///
  /// **Parameters:**
  /// - `pitch` (in): Default voice pitch
  ///
  /// **Returns:**
  /// - 0 on success, otherwise a negative error value.
  ///
  /// **Return values:**
  /// - `TTS_SETTING_ERROR_NONE`: Success.
  /// - `TTS_SETTING_ERROR_INVALID_PARAMETER`: Invalid parameter.
  /// - `TTS_SETTING_ERROR_INVALID_STATE`: Not initialized.
  /// - `TTS_SETTING_ERROR_OPERATION_FAILED`: Operation failure.
  /// - `TTS_SETTING_ERROR_NOT_SUPPORTED_FEATURE`: Not supported feature.
  /// - `TTS_SETTING_ERROR_NOT_SUPPORTED`: TTS NOT supported
  ///
  /// **See also:**
  /// - `tts_setting_get_pitch_range()`
  /// - `tts_setting_get_pitch()`
  int tts_setting_set_pitch(
    int pitch,
  ) {
    return _tts_setting_set_pitch(
      pitch,
    );
  }

  late final _tts_setting_set_pitchPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Int)>>(
          'tts_setting_set_pitch');
  late final _tts_setting_set_pitch =
      _tts_setting_set_pitchPtr.asFunction<int Function(int)>();

  /// Gets a current background volume ratio.
  ///
  /// **Parameters:**
  /// - `ratio` (out): Current background volume ratio
  ///
  /// **Returns:**
  /// - 0 on success, otherwise a negative error value.
  ///
  /// **Return values:**
  /// - `TTS_SETTING_ERROR_NONE`: Success.
  /// - `TTS_SETTING_ERROR_INVALID_PARAMETER`: Invalid parameter.
  /// - `TTS_SETTING_ERROR_INVALID_STATE`: Not initialized.
  /// - `TTS_SETTING_ERROR_OPERATION_FAILED`: Operation failure.
  /// - `TTS_SETTING_ERROR_NOT_SUPPORTED_FEATURE`: Not supported feature.
  /// - `TTS_SETTING_ERROR_NOT_SUPPORTED`: TTS NOT supported
  ///
  /// **See also:**
  /// - `tts_setting_set_background_volume_ratio()`
  int tts_setting_get_background_volume_ratio(
    ffi.Pointer<ffi.Double> ratio,
  ) {
    return _tts_setting_get_background_volume_ratio(
      ratio,
    );
  }

  late final _tts_setting_get_background_volume_ratioPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<ffi.Double>)>>(
          'tts_setting_get_background_volume_ratio');
  late final _tts_setting_get_background_volume_ratio =
      _tts_setting_get_background_volume_ratioPtr
          .asFunction<int Function(ffi.Pointer<ffi.Double>)>();

  /// Sets a current background volume ratio.
  ///
  /// **Parameters:**
  /// - `ratio` (in): Current background volume ratio (Range 0.0 ~ 1.0)
  ///
  /// **Returns:**
  /// - 0 on success, otherwise a negative error value.
  ///
  /// **Return values:**
  /// - `TTS_SETTING_ERROR_NONE`: Success.
  /// - `TTS_SETTING_ERROR_INVALID_PARAMETER`: Invalid parameter.
  /// - `TTS_SETTING_ERROR_INVALID_STATE`: Not initialized.
  /// - `TTS_SETTING_ERROR_OPERATION_FAILED`: Operation failure.
  /// - `TTS_SETTING_ERROR_NOT_SUPPORTED_FEATURE`: Not supported feature.
  /// - `TTS_SETTING_ERROR_NOT_SUPPORTED`: TTS NOT supported
  ///
  /// **See also:**
  /// - `tts_setting_get_background_volume_ratio()`
  int tts_setting_set_background_volume_ratio(
    double ratio,
  ) {
    return _tts_setting_set_background_volume_ratio(
      ratio,
    );
  }

  late final _tts_setting_set_background_volume_ratioPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Double)>>(
          'tts_setting_set_background_volume_ratio');
  late final _tts_setting_set_background_volume_ratio =
      _tts_setting_set_background_volume_ratioPtr
          .asFunction<int Function(double)>();

  /// Registers a callback function to be called when engine information is changed
  ///
  /// **Parameters:**
  /// - `callback` (in): The callback function to register
  /// - `user_data` (in): The user data to be passed to the callback function
  ///
  /// **Returns:**
  /// - 0 on success, otherwise a negative error value
  ///
  /// **Return values:**
  /// - `TTS_SETTING_ERROR_NONE`: Successful
  /// - `TTS_SETTING_ERROR_INVALID_PARAMETER`: Invalid parameter
  /// - `TTS_SETTING_ERROR_OPERATION_FAILED`: Invalid state
  /// - `TTS_SETTING_ERROR_NOT_SUPPORTED`: TTS NOT supported
  ///
  /// **See also:**
  /// - `tts_setting_engine_changed_cb()`
  /// - `tts_setting_unset_engine_changed_cb()`
  int tts_setting_set_engine_changed_cb(
    tts_setting_engine_changed_cb callback,
    ffi.Pointer<ffi.Void> user_data,
  ) {
    return _tts_setting_set_engine_changed_cb(
      callback,
      user_data,
    );
  }

  late final _tts_setting_set_engine_changed_cbPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(tts_setting_engine_changed_cb,
              ffi.Pointer<ffi.Void>)>>('tts_setting_set_engine_changed_cb');
  late final _tts_setting_set_engine_changed_cb =
      _tts_setting_set_engine_changed_cbPtr.asFunction<
          int Function(tts_setting_engine_changed_cb, ffi.Pointer<ffi.Void>)>();

  /// Unregisters the callback function
  ///
  /// **Returns:**
  /// - 0 on success, otherwise a negative error value
  ///
  /// **Return values:**
  /// - `TTS_SETTING_ERROR_NONE`: Successful
  /// - `TTS_SETTING_ERROR_OPERATION_FAILED`: Invalid state
  /// - `TTS_SETTING_ERROR_NOT_SUPPORTED`: TTS NOT supported
  ///
  /// **See also:**
  /// - `tts_setting_set_engine_changed_cb()`
  int tts_setting_unset_engine_changed_cb() {
    return _tts_setting_unset_engine_changed_cb();
  }

  late final _tts_setting_unset_engine_changed_cbPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function()>>(
          'tts_setting_unset_engine_changed_cb');
  late final _tts_setting_unset_engine_changed_cb =
      _tts_setting_unset_engine_changed_cbPtr.asFunction<int Function()>();

  /// Registers a callback function to be called when default voice is changed
  ///
  /// **Parameters:**
  /// - `callback` (in): The callback function to register
  /// - `user_data` (in): The user data to be passed to the callback function
  ///
  /// **Returns:**
  /// - 0 on success, otherwise a negative error value
  ///
  /// **Return values:**
  /// - `TTS_SETTING_ERROR_NONE`: Successful
  /// - `TTS_SETTING_ERROR_INVALID_PARAMETER`: Invalid parameter
  /// - `TTS_SETTING_ERROR_OPERATION_FAILED`: Invalid state
  /// - `TTS_SETTING_ERROR_NOT_SUPPORTED`: TTS NOT supported
  ///
  /// **See also:**
  /// - `tts_setting_voice_changed_cb()`
  /// - `tts_setting_unset_voice_changed_cb()`
  int tts_setting_set_voice_changed_cb(
    tts_setting_voice_changed_cb callback,
    ffi.Pointer<ffi.Void> user_data,
  ) {
    return _tts_setting_set_voice_changed_cb(
      callback,
      user_data,
    );
  }

  late final _tts_setting_set_voice_changed_cbPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(tts_setting_voice_changed_cb,
              ffi.Pointer<ffi.Void>)>>('tts_setting_set_voice_changed_cb');
  late final _tts_setting_set_voice_changed_cb =
      _tts_setting_set_voice_changed_cbPtr.asFunction<
          int Function(tts_setting_voice_changed_cb, ffi.Pointer<ffi.Void>)>();

  /// Unregisters the callback function
  ///
  /// **Returns:**
  /// - 0 on success, otherwise a negative error value
  ///
  /// **Return values:**
  /// - `TTS_SETTING_ERROR_NONE`: Successful
  /// - `TTS_SETTING_ERROR_OPERATION_FAILED`: Invalid state
  /// - `TTS_SETTING_ERROR_NOT_SUPPORTED`: TTS NOT supported
  ///
  /// **See also:**
  /// - `tts_setting_set_voice_changed_cb()`
  int tts_setting_unset_voice_changed_cb() {
    return _tts_setting_unset_voice_changed_cb();
  }

  late final _tts_setting_unset_voice_changed_cbPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function()>>(
          'tts_setting_unset_voice_changed_cb');
  late final _tts_setting_unset_voice_changed_cb =
      _tts_setting_unset_voice_changed_cbPtr.asFunction<int Function()>();

  /// Registers a callback function to be called when default speed is changed
  ///
  /// **Parameters:**
  /// - `callback` (in): The callback function to register
  /// - `user_data` (in): The user data to be passed to the callback function
  ///
  /// **Returns:**
  /// - 0 on success, otherwise a negative error value
  ///
  /// **Return values:**
  /// - `TTS_SETTING_ERROR_NONE`: Successful
  /// - `TTS_SETTING_ERROR_INVALID_PARAMETER`: Invalid parameter
  /// - `TTS_SETTING_ERROR_OPERATION_FAILED`: Invalid state
  /// - `TTS_SETTING_ERROR_NOT_SUPPORTED`: TTS NOT supported
  ///
  /// **See also:**
  /// - `tts_setting_speed_changed_cb()`
  /// - `tts_setting_unset_speed_changed_cb()`
  int tts_setting_set_speed_changed_cb(
    tts_setting_speed_changed_cb callback,
    ffi.Pointer<ffi.Void> user_data,
  ) {
    return _tts_setting_set_speed_changed_cb(
      callback,
      user_data,
    );
  }

  late final _tts_setting_set_speed_changed_cbPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(tts_setting_speed_changed_cb,
              ffi.Pointer<ffi.Void>)>>('tts_setting_set_speed_changed_cb');
  late final _tts_setting_set_speed_changed_cb =
      _tts_setting_set_speed_changed_cbPtr.asFunction<
          int Function(tts_setting_speed_changed_cb, ffi.Pointer<ffi.Void>)>();

  /// Unregisters the callback function
  ///
  /// **Returns:**
  /// - 0 on success, otherwise a negative error value
  ///
  /// **Return values:**
  /// - `TTS_SETTING_ERROR_NONE`: Successful
  /// - `TTS_SETTING_ERROR_OPERATION_FAILED`: Invalid state
  /// - `TTS_SETTING_ERROR_NOT_SUPPORTED`: TTS NOT supported
  ///
  /// **See also:**
  /// - `tts_setting_set_speed_changed_cb()`
  int tts_setting_unset_speed_changed_cb() {
    return _tts_setting_unset_speed_changed_cb();
  }

  late final _tts_setting_unset_speed_changed_cbPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function()>>(
          'tts_setting_unset_speed_changed_cb');
  late final _tts_setting_unset_speed_changed_cb =
      _tts_setting_unset_speed_changed_cbPtr.asFunction<int Function()>();

  /// Registers a callback function to be called when default pitch is changed
  ///
  /// **Parameters:**
  /// - `callback` (in): The callback function to register
  /// - `user_data` (in): The user data to be passed to the callback function
  ///
  /// **Returns:**
  /// - 0 on success, otherwise a negative error value
  ///
  /// **Return values:**
  /// - `TTS_SETTING_ERROR_NONE`: Successful
  /// - `TTS_SETTING_ERROR_INVALID_PARAMETER`: Invalid parameter
  /// - `TTS_SETTING_ERROR_OPERATION_FAILED`: Invalid state
  /// - `TTS_SETTING_ERROR_NOT_SUPPORTED`: TTS NOT supported
  ///
  /// **See also:**
  /// - `tts_setting_pitch_changed_cb()`
  /// - `tts_setting_unset_pitch_changed_cb()`
  int tts_setting_set_pitch_changed_cb(
    tts_setting_pitch_changed_cb callback,
    ffi.Pointer<ffi.Void> user_data,
  ) {
    return _tts_setting_set_pitch_changed_cb(
      callback,
      user_data,
    );
  }

  late final _tts_setting_set_pitch_changed_cbPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(tts_setting_pitch_changed_cb,
              ffi.Pointer<ffi.Void>)>>('tts_setting_set_pitch_changed_cb');
  late final _tts_setting_set_pitch_changed_cb =
      _tts_setting_set_pitch_changed_cbPtr.asFunction<
          int Function(tts_setting_pitch_changed_cb, ffi.Pointer<ffi.Void>)>();

  /// Unregisters the callback function
  ///
  /// **Returns:**
  /// - 0 on success, otherwise a negative error value
  ///
  /// **Return values:**
  /// - `TTS_SETTING_ERROR_NONE`: Successful
  /// - `TTS_SETTING_ERROR_OPERATION_FAILED`: Invalid state
  /// - `TTS_SETTING_ERROR_NOT_SUPPORTED`: TTS NOT supported
  ///
  /// **See also:**
  /// - `tts_setting_set_pitch_changed_cb()`
  int tts_setting_unset_pitch_changed_cb() {
    return _tts_setting_unset_pitch_changed_cb();
  }

  late final _tts_setting_unset_pitch_changed_cbPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function()>>(
          'tts_setting_unset_pitch_changed_cb');
  late final _tts_setting_unset_pitch_changed_cb =
      _tts_setting_unset_pitch_changed_cbPtr.asFunction<int Function()>();

  /// Sets a callback function to be called when current background volume is changed
  ///
  /// **Parameters:**
  /// - `callback` (in): The callback function to register
  /// - `user_data` (in): The user data to be passed to the callback function
  ///
  /// **Returns:**
  /// - 0 on success, otherwise a negative error value
  ///
  /// **Return values:**
  /// - `TTS_SETTING_ERROR_NONE`: Successful
  /// - `TTS_SETTING_ERROR_INVALID_PARAMETER`: Invalid parameter
  /// - `TTS_SETTING_ERROR_OPERATION_FAILED`: Invalid state
  /// - `TTS_SETTING_ERROR_NOT_SUPPORTED`: TTS NOT supported
  ///
  /// **See also:**
  /// - `tts_setting_background_volume_ratio_changed_cb()`
  /// - `tts_setting_unset_background_volume_ratio_changed_cb()`
  int tts_setting_set_background_volume_ratio_changed_cb(
    tts_setting_background_volume_ratio_changed_cb callback,
    ffi.Pointer<ffi.Void> user_data,
  ) {
    return _tts_setting_set_background_volume_ratio_changed_cb(
      callback,
      user_data,
    );
  }

  late final _tts_setting_set_background_volume_ratio_changed_cbPtr = _lookup<
          ffi.NativeFunction<
              ffi.Int Function(tts_setting_background_volume_ratio_changed_cb,
                  ffi.Pointer<ffi.Void>)>>(
      'tts_setting_set_background_volume_ratio_changed_cb');
  late final _tts_setting_set_background_volume_ratio_changed_cb =
      _tts_setting_set_background_volume_ratio_changed_cbPtr.asFunction<
          int Function(tts_setting_background_volume_ratio_changed_cb,
              ffi.Pointer<ffi.Void>)>();

  /// Unsets the callback function
  ///
  /// **Returns:**
  /// - 0 on success, otherwise a negative error value
  ///
  /// **Return values:**
  /// - `TTS_SETTING_ERROR_NONE`: Successful
  /// - `TTS_SETTING_ERROR_OPERATION_FAILED`: Invalid state
  /// - `TTS_SETTING_ERROR_NOT_SUPPORTED`: TTS NOT supported
  ///
  /// **See also:**
  /// - `tts_setting_set_background_volume_ratio_changed_cb()`
  int tts_setting_unset_background_volume_ratio_changed_cb() {
    return _tts_setting_unset_background_volume_ratio_changed_cb();
  }

  late final _tts_setting_unset_background_volume_ratio_changed_cbPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function()>>(
          'tts_setting_unset_background_volume_ratio_changed_cb');
  late final _tts_setting_unset_background_volume_ratio_changed_cb =
      _tts_setting_unset_background_volume_ratio_changed_cbPtr
          .asFunction<int Function()>();
}

/// Enumerations of error codes.
/// @nodoc
abstract class tts_setting_error_e {
  /// < Success, No error
  static const int TTS_SETTING_ERROR_NONE = 0;

  /// < Out of Memory
  static const int TTS_SETTING_ERROR_OUT_OF_MEMORY = -12;

  /// < I/O error
  static const int TTS_SETTING_ERROR_IO_ERROR = -5;

  /// < Invalid parameter
  static const int TTS_SETTING_ERROR_INVALID_PARAMETER = -22;

  /// < Permission denied
  static const int TTS_SETTING_ERROR_PERMISSION_DENIED = -13;

  /// < TTS is NOT supported
  static const int TTS_SETTING_ERROR_NOT_SUPPORTED = -1073741822;

  /// < Invalid state
  static const int TTS_SETTING_ERROR_INVALID_STATE = -49348607;

  /// < Invalid voice
  static const int TTS_SETTING_ERROR_INVALID_VOICE = -49348606;

  /// < No available TTS-engine
  static const int TTS_SETTING_ERROR_ENGINE_NOT_FOUND = -49348605;

  /// < Operation failed
  static const int TTS_SETTING_ERROR_OPERATION_FAILED = -49348604;

  /// < Not supported feature of current engine
  static const int TTS_SETTING_ERROR_NOT_SUPPORTED_FEATURE = -49348602;
}

/// Called to get a engine information.
///
/// **Parameters:**
/// - `engine_id` (in): Engine id.
/// - `engine_name` (in): Engine name.
/// - `setting_path` (in): Gadget path of engine specific setting.
/// - `user_data` (in): User data passed from the tts_setting_foreach_supported_engines().
///
/// **Returns:**
/// - `true` to continue with the next iteration of the loop, `false` to break out of the loop.
///
/// **Preconditions:**
/// - tts_setting_foreach_supported_engines() will invoke this callback.
///
/// **See also:**
/// - `tts_setting_foreach_supported_engines()`
/// @nodoc
typedef tts_setting_supported_engine_cb
    = ffi.Pointer<ffi.NativeFunction<tts_setting_supported_engine_cbFunction>>;
/// @nodoc
typedef tts_setting_supported_engine_cbFunction = ffi.Bool Function(
    ffi.Pointer<ffi.Char> engine_id,
    ffi.Pointer<ffi.Char> engine_name,
    ffi.Pointer<ffi.Char> setting_path,
    ffi.Pointer<ffi.Void> user_data);
/// @nodoc
typedef Darttts_setting_supported_engine_cbFunction = bool Function(
    ffi.Pointer<ffi.Char> engine_id,
    ffi.Pointer<ffi.Char> engine_name,
    ffi.Pointer<ffi.Char> setting_path,
    ffi.Pointer<ffi.Void> user_data);

/// Called to get a voice.
///
/// **Parameters:**
/// - `engine_id` (in): Engine id
/// - `language` (in): A language is specified as an ISO 3166 alpha-2 two letter country-code followed by ISO 639-1 for the two-letter language code. For example, "ko_KR" for Korean, "en_US" for American English..
/// - `voice_type` (in): Voice type
/// - `user_data` (in): User data passed from the tts_setting_foreach_supported_voices()
///
/// **Returns:**
/// - `true` to continue with the next iteration of the loop, `false` to break out of the loop.
///
/// **Preconditions:**
/// - tts_setting_foreach_supported_voices() will invoke this callback.
///
/// **See also:**
/// - `tts_setting_foreach_supported_voices()`
/// @nodoc
typedef tts_setting_supported_voice_cb
    = ffi.Pointer<ffi.NativeFunction<tts_setting_supported_voice_cbFunction>>;
/// @nodoc
typedef tts_setting_supported_voice_cbFunction = ffi.Bool Function(
    ffi.Pointer<ffi.Char> engine_id,
    ffi.Pointer<ffi.Char> language,
    ffi.Int voice_type,
    ffi.Pointer<ffi.Void> user_data);
/// @nodoc
typedef Darttts_setting_supported_voice_cbFunction = bool Function(
    ffi.Pointer<ffi.Char> engine_id,
    ffi.Pointer<ffi.Char> language,
    int voice_type,
    ffi.Pointer<ffi.Void> user_data);

/// Called when the default engine is changed.
///
/// **Parameters:**
/// - `engine_id` (in): Engine id
/// - `user_data` (in): The user data passed from the callback registration function
///
/// **Preconditions:**
/// - An application registers this callback using tts_setting_set_engine_changed_cb().
///
/// **See also:**
/// - `tts_setting_set_engine_changed_cb()`
/// - `tts_setting_unset_engine_changed_cb()`
/// @nodoc
typedef tts_setting_engine_changed_cb
    = ffi.Pointer<ffi.NativeFunction<tts_setting_engine_changed_cbFunction>>;
/// @nodoc
typedef tts_setting_engine_changed_cbFunction = ffi.Void Function(
    ffi.Pointer<ffi.Char> engine_id, ffi.Pointer<ffi.Void> user_data);
/// @nodoc
typedef Darttts_setting_engine_changed_cbFunction = void Function(
    ffi.Pointer<ffi.Char> engine_id, ffi.Pointer<ffi.Void> user_data);

/// Called when the default voice is changed.
///
/// **Parameters:**
/// - `language` (in): A language
/// - `voice_type` (in): Voice type
/// - `auto_voice` (in): Auto voice
/// - `user_data` (in): The user data passed from the callback registration function
///
/// **Preconditions:**
/// - An application registers this callback using registration function.
///
/// **See also:**
/// - `tts_setting_set_voice_changed_cb()`
/// - `tts_setting_unset_voice_changed_cb()`
/// @nodoc
typedef tts_setting_voice_changed_cb
    = ffi.Pointer<ffi.NativeFunction<tts_setting_voice_changed_cbFunction>>;
/// @nodoc
typedef tts_setting_voice_changed_cbFunction = ffi.Void Function(
    ffi.Pointer<ffi.Char> language,
    ffi.Int voice_type,
    ffi.Bool auto_voice,
    ffi.Pointer<ffi.Void> user_data);
/// @nodoc
typedef Darttts_setting_voice_changed_cbFunction = void Function(
    ffi.Pointer<ffi.Char> language,
    int voice_type,
    bool auto_voice,
    ffi.Pointer<ffi.Void> user_data);

/// Called when the default speed is changed.
///
/// **Parameters:**
/// - `speed` (in): Default speed
/// - `user_data` (in): The user data passed from the callback registration function
///
/// **Preconditions:**
/// - An application registers this callback using registration function.
///
/// **See also:**
/// - `tts_setting_set_speed_changed_cb()`
/// - `tts_setting_unset_speed_changed_cb()`
/// @nodoc
typedef tts_setting_speed_changed_cb
    = ffi.Pointer<ffi.NativeFunction<tts_setting_speed_changed_cbFunction>>;
/// @nodoc
typedef tts_setting_speed_changed_cbFunction = ffi.Void Function(
    ffi.Int speed, ffi.Pointer<ffi.Void> user_data);
/// @nodoc
typedef Darttts_setting_speed_changed_cbFunction = void Function(
    int speed, ffi.Pointer<ffi.Void> user_data);

/// Called when the default pitch is changed.
///
/// **Parameters:**
/// - `pitch` (in): Default pitch
/// - `user_data` (in): The user data passed from the callback registration function
///
/// **Preconditions:**
/// - An application registers this callback using registration function.
///
/// **See also:**
/// - `tts_setting_set_pitch_changed_cb()`
/// - `tts_setting_unset_pitch_changed_cb()`
/// @nodoc
typedef tts_setting_pitch_changed_cb
    = ffi.Pointer<ffi.NativeFunction<tts_setting_pitch_changed_cbFunction>>;
/// @nodoc
typedef tts_setting_pitch_changed_cbFunction = ffi.Void Function(
    ffi.Int pitch, ffi.Pointer<ffi.Void> user_data);
/// @nodoc
typedef Darttts_setting_pitch_changed_cbFunction = void Function(
    int pitch, ffi.Pointer<ffi.Void> user_data);

/// Called when the current background volume ratio is changed.
///
/// **Parameters:**
/// - `ratio` (in): Current background volume ratio
/// - `user_data` (in): The user data passed from the callback registration function
///
/// **Preconditions:**
/// - An application registers this callback using registration function.
///
/// **See also:**
/// - `tts_setting_set_background_volume_ratio_changed_cb()`
/// - `tts_setting_unset_background_volume_ratio_changed_cb()`
/// @nodoc
typedef tts_setting_background_volume_ratio_changed_cb = ffi.Pointer<
    ffi.NativeFunction<tts_setting_background_volume_ratio_changed_cbFunction>>;
/// @nodoc
typedef tts_setting_background_volume_ratio_changed_cbFunction = ffi.Void
    Function(ffi.Double ratio, ffi.Pointer<ffi.Void> user_data);
/// @nodoc
typedef Darttts_setting_background_volume_ratio_changed_cbFunction = void
    Function(double ratio, ffi.Pointer<ffi.Void> user_data);

/// @nodoc
const int TTS_SETTING_VOICE_TYPE_MALE = 1;

/// @nodoc
const int TTS_SETTING_VOICE_TYPE_FEMALE = 2;

/// @nodoc
const int TTS_SETTING_VOICE_TYPE_CHILD = 3;
