/// {@category 9.0/tizen}
library tizen_interop_9_0.stt_setting;

// Copyright 2021 Samsung Electronics Co., Ltd. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// ignore_for_file: type=lint, unused_element, unused_field

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
import 'dart:ffi' as ffi;

/// Dart bindings for Tizen stt setting APIs.
/// {@category 9.0/tizen}
class Tizen90SttSetting {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  Tizen90SttSetting(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  Tizen90SttSetting.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  /// Initialize STT setting.
  ///
  /// **Remarks:**
  /// - If the function succeeds, `stt` setting must be released with stt_setting_finalize().
  ///
  /// **Returns:**
  /// - 0 on success, otherwise a negative error value.
  ///
  /// **Return values:**
  /// - `STT_SETTING_ERROR_NONE`: Success.
  /// - `STT_SETTING_ERROR_TIMED_OUT`: stt service is blocked or stt service do not exist.
  /// - `STT_SETTING_ERROR_INVALID_STATE`: STT setting has Already been initialized.
  /// - `STT_SETTING_ERROR_ENGINE_NOT_FOUND`: No available stt-engine. Engine should be installed.
  /// - `STT_SETTING_ERROR_NOT_SUPPORTED`: STT NOT supported
  ///
  /// **See also:**
  /// - `stt_setting_finalize()`
  int stt_setting_initialize() {
    return _stt_setting_initialize();
  }

  late final _stt_setting_initializePtr =
      _lookup<ffi.NativeFunction<ffi.Int Function()>>('stt_setting_initialize');
  late final _stt_setting_initialize =
      _stt_setting_initializePtr.asFunction<int Function()>();

  /// finalize stt setting and disconnect to stt-service.
  ///
  /// **Returns:**
  /// - 0 on success, otherwise a negative error value.
  ///
  /// **Return values:**
  /// - `STT_SETTING_ERROR_NONE`: Success.
  /// - `STT_SETTING_ERROR_INVALID_STATE`: STT Not initialized.
  /// - `STT_SETTING_ERROR_OPERATION_FAILED`: Operation failure.
  /// - `STT_SETTING_ERROR_NOT_SUPPORTED`: STT NOT supported
  ///
  /// **See also:**
  /// - `stt_setting_initialize()`
  int stt_setting_finalize() {
    return _stt_setting_finalize();
  }

  late final _stt_setting_finalizePtr =
      _lookup<ffi.NativeFunction<ffi.Int Function()>>('stt_setting_finalize');
  late final _stt_setting_finalize =
      _stt_setting_finalizePtr.asFunction<int Function()>();

  /// Retrieve supported engine informations using callback function.
  ///
  /// **Parameters:**
  /// - `callback` (in): callback function
  /// - `user_data` (in): User data to be passed to the callback function.
  ///
  /// **Returns:**
  /// - 0 on success, otherwise a negative error value.
  ///
  /// **Return values:**
  /// - `STT_SETTING_ERROR_NONE`: Success.
  /// - `STT_SETTING_ERROR_INVALID_PARAMETER`: Invalid parameter.
  /// - `STT_SETTING_ERROR_INVALID_STATE`: STT Not initialized.
  /// - `STT_SETTING_ERROR_NOT_SUPPORTED`: STT NOT supported
  ///
  /// **Postconditions:**
  /// - This function invokes stt_setting_supported_engine_cb() repeatedly for getting engine information.
  ///
  /// **See also:**
  /// - `stt_setting_supported_engine_cb()`
  int stt_setting_foreach_supported_engines(
    stt_setting_supported_engine_cb callback,
    ffi.Pointer<ffi.Void> user_data,
  ) {
    return _stt_setting_foreach_supported_engines(
      callback,
      user_data,
    );
  }

  late final _stt_setting_foreach_supported_enginesPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(stt_setting_supported_engine_cb,
              ffi.Pointer<ffi.Void>)>>('stt_setting_foreach_supported_engines');
  late final _stt_setting_foreach_supported_engines =
      _stt_setting_foreach_supported_enginesPtr.asFunction<
          int Function(
              stt_setting_supported_engine_cb, ffi.Pointer<ffi.Void>)>();

  /// Get current engine id.
  ///
  /// **Remarks:**
  /// - If the function is success, `engine_id` must be released with free() by you.
  ///
  /// **Parameters:**
  /// - `engine_id` (out): engine id.
  ///
  /// **Returns:**
  /// - 0 on success, otherwise a negative error value.
  ///
  /// **Return values:**
  /// - `STT_SETTING_ERROR_NONE`: Success.
  /// - `STT_SETTING_ERROR_OUT_OF_MEMORY`: Out of memory.
  /// - `STT_SETTING_ERROR_INVALID_PARAMETER`: Invalid parameter.
  /// - `STT_SETTING_ERROR_INVALID_STATE`: STT Not initialized.
  /// - `STT_SETTING_ERROR_OPERATION_FAILED`: Operation failure.
  /// - `STT_SETTING_ERROR_NOT_SUPPORTED`: STT NOT supported
  ///
  /// **See also:**
  /// - `stt_setting_set_engine()`
  int stt_setting_get_engine(
    ffi.Pointer<ffi.Pointer<ffi.Char>> engine_id,
  ) {
    return _stt_setting_get_engine(
      engine_id,
    );
  }

  late final _stt_setting_get_enginePtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(
              ffi.Pointer<ffi.Pointer<ffi.Char>>)>>('stt_setting_get_engine');
  late final _stt_setting_get_engine = _stt_setting_get_enginePtr
      .asFunction<int Function(ffi.Pointer<ffi.Pointer<ffi.Char>>)>();

  /// Set current engine id.
  ///
  /// **Parameters:**
  /// - `engine_id` (in): engine id.
  ///
  /// **Returns:**
  /// - 0 on success, otherwise a negative error value.
  ///
  /// **Return values:**
  /// - `STT_SETTING_ERROR_NONE`: Success.
  /// - `STT_SETTING_ERROR_INVALID_PARAMETER`: Invalid parameter.
  /// - `STT_SETTING_ERROR_INVALID_STATE`: STT Not initialized.
  /// - `STT_SETTING_ERROR_OPERATION_FAILED`: Operation failure.
  /// - `STT_SETTING_ERROR_NOT_SUPPORTED`: STT NOT supported
  ///
  /// **See also:**
  /// - `stt_setting_get_engine()`
  int stt_setting_set_engine(
    ffi.Pointer<ffi.Char> engine_id,
  ) {
    return _stt_setting_set_engine(
      engine_id,
    );
  }

  late final _stt_setting_set_enginePtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<ffi.Char>)>>(
          'stt_setting_set_engine');
  late final _stt_setting_set_engine = _stt_setting_set_enginePtr
      .asFunction<int Function(ffi.Pointer<ffi.Char>)>();

  /// Get supported languages of current engine.
  ///
  /// **Parameters:**
  /// - `callback` (in): callback function.
  /// - `user_data` (in): User data to be passed to the callback function.
  ///
  /// **Returns:**
  /// - 0 on success, otherwise a negative error value.
  ///
  /// **Return values:**
  /// - `STT_SETTING_ERROR_NONE`: Success.
  /// - `STT_SETTING_ERROR_INVALID_PARAMETER`: Invalid parameter.
  /// - `STT_SETTING_ERROR_INVALID_STATE`: STT Not initialized.
  /// - `STT_SETTING_ERROR_OPERATION_FAILED`: Operation failure.
  /// - `STT_SETTING_ERROR_NOT_SUPPORTED`: STT NOT supported
  ///
  /// **Postconditions:**
  /// - This function invokes stt_setting_supported_language_cb() repeatedly for getting supported languages.
  ///
  /// **See also:**
  /// - `stt_setting_supported_language_cb()`
  int stt_setting_foreach_supported_languages(
    stt_setting_supported_language_cb callback,
    ffi.Pointer<ffi.Void> user_data,
  ) {
    return _stt_setting_foreach_supported_languages(
      callback,
      user_data,
    );
  }

  late final _stt_setting_foreach_supported_languagesPtr = _lookup<
          ffi.NativeFunction<
              ffi.Int Function(
                  stt_setting_supported_language_cb, ffi.Pointer<ffi.Void>)>>(
      'stt_setting_foreach_supported_languages');
  late final _stt_setting_foreach_supported_languages =
      _stt_setting_foreach_supported_languagesPtr.asFunction<
          int Function(
              stt_setting_supported_language_cb, ffi.Pointer<ffi.Void>)>();

  /// Get a default language of current engine.
  ///
  /// **Remarks:**
  /// - If the function is success, `language` must be released with free() by you.
  ///
  /// **Parameters:**
  /// - `language` (out): current language
  ///
  /// **Returns:**
  /// - 0 on success, otherwise a negative error value.
  ///
  /// **Return values:**
  /// - `STT_SETTING_ERROR_NONE`: Success.
  /// - `STT_SETTING_ERROR_OUT_OF_MEMORY`: Out of memory.
  /// - `STT_SETTING_ERROR_INVALID_PARAMETER`: Invalid parameter.
  /// - `STT_SETTING_ERROR_INVALID_STATE`: STT Not initialized.
  /// - `STT_SETTING_ERROR_OPERATION_FAILED`: Operation failure.
  /// - `STT_SETTING_ERROR_NOT_SUPPORTED`: STT NOT supported
  ///
  /// **See also:**
  /// - `stt_setting_set_default_language()`
  int stt_setting_get_default_language(
    ffi.Pointer<ffi.Pointer<ffi.Char>> language,
  ) {
    return _stt_setting_get_default_language(
      language,
    );
  }

  late final _stt_setting_get_default_languagePtr = _lookup<
          ffi.NativeFunction<
              ffi.Int Function(ffi.Pointer<ffi.Pointer<ffi.Char>>)>>(
      'stt_setting_get_default_language');
  late final _stt_setting_get_default_language =
      _stt_setting_get_default_languagePtr
          .asFunction<int Function(ffi.Pointer<ffi.Pointer<ffi.Char>>)>();

  /// Set a default language of current engine.
  ///
  /// **Parameters:**
  /// - `language` (in): language
  ///
  /// **Returns:**
  /// - 0 on success, otherwise a negative error value.
  ///
  /// **Return values:**
  /// - `STT_SETTING_ERROR_NONE`: Success.
  /// - `STT_SETTING_ERROR_INVALID_PARAMETER`: Invalid parameter.
  /// - `STT_SETTING_ERROR_INVALID_STATE`: STT Not initialized.
  /// - `STT_SETTING_ERROR_OPERATION_FAILED`: Operation failure.
  /// - `STT_SETTING_ERROR_NOT_SUPPORTED`: STT NOT supported
  ///
  /// **See also:**
  /// - `stt_setting_get_default_language()`
  int stt_setting_set_default_language(
    ffi.Pointer<ffi.Char> language,
  ) {
    return _stt_setting_set_default_language(
      language,
    );
  }

  late final _stt_setting_set_default_languagePtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<ffi.Char>)>>(
          'stt_setting_set_default_language');
  late final _stt_setting_set_default_language =
      _stt_setting_set_default_languagePtr
          .asFunction<int Function(ffi.Pointer<ffi.Char>)>();

  /// Set a automatic option of language.
  ///
  /// **Parameters:**
  /// - `value` (in): The automatic option
  ///
  /// **Returns:**
  /// - 0 on success, otherwise a negative error value.
  ///
  /// **Return values:**
  /// - `STT_SETTING_ERROR_NONE`: Success.
  /// - `STT_SETTING_ERROR_INVALID_PARAMETER`: Invalid parameter.
  /// - `STT_SETTING_ERROR_INVALID_STATE`: STT Not initialized.
  /// - `STT_SETTING_ERROR_OPERATION_FAILED`: Operation failure.
  /// - `STT_SETTING_ERROR_NOT_SUPPORTED`: STT NOT supported
  ///
  /// **See also:**
  /// - `stt_setting_get_auto_language()`
  int stt_setting_set_auto_language(
    bool value,
  ) {
    return _stt_setting_set_auto_language(
      value,
    );
  }

  late final _stt_setting_set_auto_languagePtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Bool)>>(
          'stt_setting_set_auto_language');
  late final _stt_setting_set_auto_language =
      _stt_setting_set_auto_languagePtr.asFunction<int Function(bool)>();

  /// Get a automatic option of voice.
  ///
  /// **Parameters:**
  /// - `value` (out): The automatic option
  ///
  /// **Returns:**
  /// - 0 on success, otherwise a negative error value.
  ///
  /// **Return values:**
  /// - `STT_SETTING_ERROR_NONE`: Success.
  /// - `STT_SETTING_ERROR_INVALID_PARAMETER`: Invalid parameter.
  /// - `STT_SETTING_ERROR_INVALID_STATE`: STT Not initialized.
  /// - `STT_SETTING_ERROR_OPERATION_FAILED`: Operation failure.
  /// - `STT_SETTING_ERROR_NOT_SUPPORTED`: STT NOT supported
  ///
  /// **See also:**
  /// - `stt_setting_set_auto_language()`
  int stt_setting_get_auto_language(
    ffi.Pointer<ffi.Bool> value,
  ) {
    return _stt_setting_get_auto_language(
      value,
    );
  }

  late final _stt_setting_get_auto_languagePtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<ffi.Bool>)>>(
          'stt_setting_get_auto_language');
  late final _stt_setting_get_auto_language = _stt_setting_get_auto_languagePtr
      .asFunction<int Function(ffi.Pointer<ffi.Bool>)>();

  /// Get silence detection.
  ///
  /// **Parameters:**
  /// - `value` (out): Value.
  ///
  /// **Returns:**
  /// - 0 on success, otherwise a negative error value
  ///
  /// **Return values:**
  /// - `STT_SETTING_ERROR_NONE`: Success.
  /// - `STT_SETTING_ERROR_INVALID_PARAMETER`: Invalid parameter.
  /// - `STT_SETTING_ERROR_INVALID_STATE`: STT Not initialized.
  /// - `STT_SETTING_ERROR_OPERATION_FAILED`: Operation failure.
  /// - `STT_SETTING_ERROR_NOT_SUPPORTED`: STT NOT supported
  ///
  /// **See also:**
  /// - `stt_setting_set_silence_detection()`
  int stt_setting_get_silence_detection(
    ffi.Pointer<ffi.Bool> value,
  ) {
    return _stt_setting_get_silence_detection(
      value,
    );
  }

  late final _stt_setting_get_silence_detectionPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<ffi.Bool>)>>(
          'stt_setting_get_silence_detection');
  late final _stt_setting_get_silence_detection =
      _stt_setting_get_silence_detectionPtr
          .asFunction<int Function(ffi.Pointer<ffi.Bool>)>();

  /// Set silence detection.
  ///
  /// **Parameters:**
  /// - `value` (in): Value.
  ///
  /// **Returns:**
  /// - 0 on success, otherwise a negative error value
  ///
  /// **Return values:**
  /// - `STT_SETTING_ERROR_NONE`: Success.
  /// - `STT_SETTING_ERROR_INVALID_PARAMETER`: Invalid parameter.
  /// - `STT_SETTING_ERROR_INVALID_STATE`: STT Not initialized.
  /// - `STT_SETTING_ERROR_OPERATION_FAILED`: Operation failure.
  /// - `STT_SETTING_ERROR_NOT_SUPPORTED`: STT NOT supported
  ///
  /// **See also:**
  /// - `stt_setting_get_silence_detection()`
  int stt_setting_set_silence_detection(
    bool value,
  ) {
    return _stt_setting_set_silence_detection(
      value,
    );
  }

  late final _stt_setting_set_silence_detectionPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Bool)>>(
          'stt_setting_set_silence_detection');
  late final _stt_setting_set_silence_detection =
      _stt_setting_set_silence_detectionPtr.asFunction<int Function(bool)>();

  /// Registers a callback function to be called when engine information is changed
  ///
  /// **Parameters:**
  /// - `callback` (in): The callback function to register
  /// - `user_data` (in): The user data to be passed to the callback function
  ///
  /// **Returns:**
  /// - 0 on success, otherwise a negative error value
  ///
  /// **Return values:**
  /// - `STT_SETTING_ERROR_NONE`: Successful
  /// - `STT_SETTING_ERROR_INVALID_PARAMETER`: Invalid parameter
  /// - `STT_SETTING_ERROR_OPERATION_FAILED`: Invalid state
  /// - `STT_SETTING_ERROR_NOT_SUPPORTED`: STT NOT supported
  ///
  /// **See also:**
  /// - `stt_setting_engine_changed_cb()`
  /// - `stt_setting_unset_engine_changed_cb()`
  int stt_setting_set_engine_changed_cb(
    stt_setting_engine_changed_cb callback,
    ffi.Pointer<ffi.Void> user_data,
  ) {
    return _stt_setting_set_engine_changed_cb(
      callback,
      user_data,
    );
  }

  late final _stt_setting_set_engine_changed_cbPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(stt_setting_engine_changed_cb,
              ffi.Pointer<ffi.Void>)>>('stt_setting_set_engine_changed_cb');
  late final _stt_setting_set_engine_changed_cb =
      _stt_setting_set_engine_changed_cbPtr.asFunction<
          int Function(stt_setting_engine_changed_cb, ffi.Pointer<ffi.Void>)>();

  /// Unregisters the callback function
  ///
  /// **Returns:**
  /// - 0 on success, otherwise a negative error value
  ///
  /// **Return values:**
  /// - `STT_SETTING_ERROR_NONE`: Successful
  /// - `STT_SETTING_ERROR_OPERATION_FAILED`: Invalid state
  ///
  /// **See also:**
  /// - `stt_setting_set_engine_changed_cb()`
  int stt_setting_unset_engine_changed_cb() {
    return _stt_setting_unset_engine_changed_cb();
  }

  late final _stt_setting_unset_engine_changed_cbPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function()>>(
          'stt_setting_unset_engine_changed_cb');
  late final _stt_setting_unset_engine_changed_cb =
      _stt_setting_unset_engine_changed_cbPtr.asFunction<int Function()>();

  /// Registers a callback function to be called when stt configure is changed
  ///
  /// **Parameters:**
  /// - `callback` (in): The callback function to register
  /// - `user_data` (in): The user data to be passed to the callback function
  ///
  /// **Returns:**
  /// - 0 on success, otherwise a negative error value
  ///
  /// **Return values:**
  /// - `STT_SETTING_ERROR_NONE`: Successful
  /// - `STT_SETTING_ERROR_INVALID_PARAMETER`: Invalid parameter
  /// - `STT_SETTING_ERROR_OPERATION_FAILED`: Invalid state
  /// - `STT_SETTING_ERROR_NOT_SUPPORTED`: STT NOT supported
  ///
  /// **See also:**
  /// - `stt_setting_config_changed_cb()`
  /// - `stt_setting_unset_config_changed_cb()`
  int stt_setting_set_config_changed_cb(
    stt_setting_config_changed_cb callback,
    ffi.Pointer<ffi.Void> user_data,
  ) {
    return _stt_setting_set_config_changed_cb(
      callback,
      user_data,
    );
  }

  late final _stt_setting_set_config_changed_cbPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(stt_setting_config_changed_cb,
              ffi.Pointer<ffi.Void>)>>('stt_setting_set_config_changed_cb');
  late final _stt_setting_set_config_changed_cb =
      _stt_setting_set_config_changed_cbPtr.asFunction<
          int Function(stt_setting_config_changed_cb, ffi.Pointer<ffi.Void>)>();

  /// Unregisters the callback function
  ///
  /// **Returns:**
  /// - 0 on success, otherwise a negative error value
  ///
  /// **Return values:**
  /// - `STT_SETTING_ERROR_NONE`: Successful
  /// - `STT_SETTING_ERROR_OPERATION_FAILED`: Invalid state
  /// - `STT_SETTING_ERROR_NOT_SUPPORTED`: STT NOT supported
  ///
  /// **See also:**
  /// - `stt_setting_set_config_changed_cb()`
  int stt_setting_unset_config_changed_cb() {
    return _stt_setting_unset_config_changed_cb();
  }

  late final _stt_setting_unset_config_changed_cbPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function()>>(
          'stt_setting_unset_config_changed_cb');
  late final _stt_setting_unset_config_changed_cb =
      _stt_setting_unset_config_changed_cbPtr.asFunction<int Function()>();
}

/// Enumerations of error codes.
/// @nodoc
abstract class stt_setting_error_e {
  /// < Successful
  static const int STT_SETTING_ERROR_NONE = 0;

  /// < Out of Memory
  static const int STT_SETTING_ERROR_OUT_OF_MEMORY = -12;

  /// < I/O error
  static const int STT_SETTING_ERROR_IO_ERROR = -5;

  /// < Invalid parameter
  static const int STT_SETTING_ERROR_INVALID_PARAMETER = -22;

  /// < No answer from the service
  static const int STT_SETTING_ERROR_TIMED_OUT = -1073741823;

  /// < Out of network
  static const int STT_SETTING_ERROR_OUT_OF_NETWORK = -100;

  /// < Permission denied
  static const int STT_SETTING_ERROR_PERMISSION_DENIED = -13;

  /// < STT is NOT supported
  static const int STT_SETTING_ERROR_NOT_SUPPORTED = -1073741822;

  /// < Invalid state
  static const int STT_SETTING_ERROR_INVALID_STATE = -49283071;

  /// < Invalid language
  static const int STT_SETTING_ERROR_INVALID_LANGUAGE = -49283070;

  /// < No available engine
  static const int STT_SETTING_ERROR_ENGINE_NOT_FOUND = -49283069;

  /// < Operation failed
  static const int STT_SETTING_ERROR_OPERATION_FAILED = -49283068;

  /// < Not supported feature of current engine
  static const int STT_SETTING_ERROR_NOT_SUPPORTED_FEATURE = -49283067;
}

/// Enumerations of setting state.
/// @nodoc
abstract class stt_setting_state_e {
  static const int STT_SETTING_STATE_NONE = 0;
  static const int STT_SETTING_STATE_READY = 1;
}

/// Called to get a engine information.
///
/// **Parameters:**
/// - `engine_id` (in): Engine id.
/// - `engine_name` (in): engine name.
/// - `setting_path` (in): gadget path of engine specific setting.
/// - `user_data` (in): User data passed from the stt_setting_foreach_supported_engines().
///
/// **Returns:**
/// - `true` to continue with the next iteration of the loop, `false` to break out of the loop.
///
/// **Preconditions:**
/// - stt_setting_foreach_supported_engines() will invoke this callback.
///
/// **See also:**
/// - `stt_setting_foreach_supported_engines()`
/// @nodoc
typedef stt_setting_supported_engine_cb
    = ffi.Pointer<ffi.NativeFunction<stt_setting_supported_engine_cbFunction>>;
/// @nodoc
typedef stt_setting_supported_engine_cbFunction = ffi.Bool Function(
    ffi.Pointer<ffi.Char> engine_id,
    ffi.Pointer<ffi.Char> engine_name,
    ffi.Pointer<ffi.Char> setting_path,
    ffi.Pointer<ffi.Void> user_data);
/// @nodoc
typedef Dartstt_setting_supported_engine_cbFunction = bool Function(
    ffi.Pointer<ffi.Char> engine_id,
    ffi.Pointer<ffi.Char> engine_name,
    ffi.Pointer<ffi.Char> setting_path,
    ffi.Pointer<ffi.Void> user_data);

/// Called to get a language.
///
/// **Parameters:**
/// - `engine_id` (in): Engine id.
/// - `language` (in): A language is specified as an ISO 3166 alpha-2 two letter country-code followed by ISO 639-1 for the two-letter language code. For example, "ko_KR" for Korean, "en_US" for American English..
/// - `user_data` (in): User data passed from the stt_setting_foreach_supported_languages().
///
/// **Returns:**
/// - `true` to continue with the next iteration of the loop, `false` to break out of the loop.
///
/// **Preconditions:**
/// - stt_setting_foreach_supported_languages() will invoke this callback.
///
/// **See also:**
/// - `stt_setting_foreach_supported_languages()`
/// @nodoc
typedef stt_setting_supported_language_cb = ffi
    .Pointer<ffi.NativeFunction<stt_setting_supported_language_cbFunction>>;
/// @nodoc
typedef stt_setting_supported_language_cbFunction = ffi.Bool Function(
    ffi.Pointer<ffi.Char> engine_id,
    ffi.Pointer<ffi.Char> language,
    ffi.Pointer<ffi.Void> user_data);
/// @nodoc
typedef Dartstt_setting_supported_language_cbFunction = bool Function(
    ffi.Pointer<ffi.Char> engine_id,
    ffi.Pointer<ffi.Char> language,
    ffi.Pointer<ffi.Void> user_data);

/// Called when the engine information is changed.
///
/// **Parameters:**
/// - `user_data` (in): The user data passed from the callback registration function
///
/// **Preconditions:**
/// - An application registers this callback using stt_setting_set_engine_changed_cb().
///
/// **See also:**
/// - `stt_setting_set_engine_changed_cb()`
/// - `stt_setting_unset_engine_changed_cb()`
/// @nodoc
typedef stt_setting_engine_changed_cb
    = ffi.Pointer<ffi.NativeFunction<stt_setting_engine_changed_cbFunction>>;
/// @nodoc
typedef stt_setting_engine_changed_cbFunction = ffi.Void Function(
    ffi.Pointer<ffi.Void> user_data);
/// @nodoc
typedef Dartstt_setting_engine_changed_cbFunction = void Function(
    ffi.Pointer<ffi.Void> user_data);

/// Called when the STT configure is changed.
///
/// **Parameters:**
/// - `user_data` (in): The user data passed from the callback registration function
///
/// **Preconditions:**
/// - An application registers this callback using stt_setting_set_config_changed_cb().
///
/// **See also:**
/// - `stt_setting_set_config_changed_cb()`
/// - `stt_setting_unset_config_changed_cb()`
/// @nodoc
typedef stt_setting_config_changed_cb
    = ffi.Pointer<ffi.NativeFunction<stt_setting_config_changed_cbFunction>>;
/// @nodoc
typedef stt_setting_config_changed_cbFunction = ffi.Void Function(
    ffi.Pointer<ffi.Void> user_data);
/// @nodoc
typedef Dartstt_setting_config_changed_cbFunction = void Function(
    ffi.Pointer<ffi.Void> user_data);
