// Copyright 2021 Samsung Electronics Co., Ltd. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// ignore_for_file: type=lint, unused_element, unused_field

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
import 'dart:ffi' as ffi;

/// Dart bindings for Tizen nnstreamer-single APIs.
class Tizen70NnstreamerSingle {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  Tizen70NnstreamerSingle(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  Tizen70NnstreamerSingle.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  /// MAIN FUNC *
  /// /
  /// /**
  /// @brief Opens an ML model and returns the instance as a handle.
  /// @details Even if the model has flexible input data dimensions,
  /// input data frames of an instance of a model should share the same dimension.
  /// @since_tizen 5.5
  /// @remarks %http://tizen.org/privilege/mediastorage is needed if @a model is relevant to media storage.
  /// @remarks %http://tizen.org/privilege/externalstorage is needed if @a model is relevant to external storage.
  /// @param[out] single This is the model handle opened. Users are required to close
  /// the given instance with ml_single_close().
  /// @param[in] model This is the path to the neural network model file.
  /// @param[in] input_info This is required if the given model has flexible input
  /// dimension, where the input dimension MUST be given
  /// before executing the model.
  /// It is required by some custom filters of NNStreamer.
  /// You may set NULL if it's not required.
  /// @param[in] output_info This is required if the given model has flexible output dimension.
  /// @param[in] nnfw The neural network framework used to open the given @a model.
  /// Set #ML_NNFW_TYPE_ANY to let it auto-detect.
  /// @param[in] hw Tell the corresponding @a nnfw to use a specific hardware.
  /// Set #ML_NNFW_HW_ANY if it does not matter.
  /// @return @c 0 on success. Otherwise a negative error value.
  /// @retval #ML_ERROR_NONE Successful.
  /// @retval #ML_ERROR_NOT_SUPPORTED Not supported.
  /// @retval #ML_ERROR_PERMISSION_DENIED The application does not have the privilege to access to the media storage or external storage.
  /// @retval #ML_ERROR_INVALID_PARAMETER Fail. The parameter is invalid.
  /// @retval #ML_ERROR_STREAMS_PIPE Failed to start the pipeline.
  /// @retval #ML_ERROR_OUT_OF_MEMORY Failed to allocate required memory.
  int ml_single_open(
    ffi.Pointer<ml_single_h> single,
    ffi.Pointer<ffi.Char> model,
    ml_tensors_info_h input_info,
    ml_tensors_info_h output_info,
    int nnfw,
    int hw,
  ) {
    return _ml_single_open(
      single,
      model,
      input_info,
      output_info,
      nnfw,
      hw,
    );
  }

  late final _ml_single_openPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(
              ffi.Pointer<ml_single_h>,
              ffi.Pointer<ffi.Char>,
              ml_tensors_info_h,
              ml_tensors_info_h,
              ffi.Int32,
              ffi.Int32)>>('ml_single_open');
  late final _ml_single_open = _ml_single_openPtr.asFunction<
      int Function(ffi.Pointer<ml_single_h>, ffi.Pointer<ffi.Char>,
          ml_tensors_info_h, ml_tensors_info_h, int, int)>();

  /// @brief Opens an ML model and returns the instance as a handle with custom options.
  /// @details Even if the model has flexible input data dimensions,
  /// input data frames of an instance of a model should share the same dimension.
  /// @since_tizen 6.5
  /// @remarks %http://tizen.org/privilege/mediastorage is needed if @a model is relevant to media storage.
  /// @remarks %http://tizen.org/privilege/externalstorage is needed if @a model is relevant to external storage.
  /// @param[out] single This is the model handle opened. Users are required to close
  /// the given instance with ml_single_close().
  /// @param[in] model This is the path to the neural network model file.
  /// @param[in] input_info This is required if the given model has flexible input
  /// dimension, where the input dimension MUST be given
  /// before executing the model.
  /// It is required by some custom filters of NNStreamer.
  /// You may set NULL if it's not required.
  /// @param[in] output_info This is required if the given model has flexible output dimension.
  /// @param[in] nnfw The neural network framework used to open the given @a model.
  /// Set #ML_NNFW_TYPE_ANY to let it auto-detect.
  /// @param[in] hw Tell the corresponding @a nnfw to use a specific hardware.
  /// Set #ML_NNFW_HW_ANY if it does not matter.
  /// @param[in] custom_option Comma separated list of options.
  /// Use this parameter to fine-tune and optimize specific neural network framework. (e.g. NumThreads:N to set the number of threads in TensorFlow-Lite)
  /// You may set NULL if it's not required.
  /// See NNStreamer documentation (https://nnstreamer.github.io/gst/nnstreamer/tensor_filter/README.html) for the details.
  /// @return @c 0 on success. Otherwise a negative error value.
  /// @retval #ML_ERROR_NONE Successful.
  /// @retval #ML_ERROR_NOT_SUPPORTED Not supported.
  /// @retval #ML_ERROR_PERMISSION_DENIED The application does not have the privilege to access to the media storage or external storage.
  /// @retval #ML_ERROR_INVALID_PARAMETER Fail. The parameter is invalid.
  /// @retval #ML_ERROR_STREAMS_PIPE Failed to start the pipeline.
  /// @retval #ML_ERROR_OUT_OF_MEMORY Failed to allocate required memory.
  int ml_single_open_full(
    ffi.Pointer<ml_single_h> single,
    ffi.Pointer<ffi.Char> model,
    ml_tensors_info_h input_info,
    ml_tensors_info_h output_info,
    int nnfw,
    int hw,
    ffi.Pointer<ffi.Char> custom_option,
  ) {
    return _ml_single_open_full(
      single,
      model,
      input_info,
      output_info,
      nnfw,
      hw,
      custom_option,
    );
  }

  late final _ml_single_open_fullPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(
              ffi.Pointer<ml_single_h>,
              ffi.Pointer<ffi.Char>,
              ml_tensors_info_h,
              ml_tensors_info_h,
              ffi.Int32,
              ffi.Int32,
              ffi.Pointer<ffi.Char>)>>('ml_single_open_full');
  late final _ml_single_open_full = _ml_single_open_fullPtr.asFunction<
      int Function(
          ffi.Pointer<ml_single_h>,
          ffi.Pointer<ffi.Char>,
          ml_tensors_info_h,
          ml_tensors_info_h,
          int,
          int,
          ffi.Pointer<ffi.Char>)>();

  /// @brief Closes the opened model handle.
  /// @details Note that this should be called before destroying the inference data by ml_tensors_data_destroy().
  /// If not, the inference engine might try to access the data that is already freed.
  /// And it causes the segmentation fault.
  /// @since_tizen 5.5
  /// @param[in] single The model handle to be closed.
  /// @return @c 0 on success. Otherwise a negative error value.
  /// @retval #ML_ERROR_NONE Successful.
  /// @retval #ML_ERROR_NOT_SUPPORTED Not supported.
  /// @retval #ML_ERROR_INVALID_PARAMETER Fail. The parameter is invalid (Pipeline is not negotiated yet.)
  int ml_single_close(
    ml_single_h single,
  ) {
    return _ml_single_close(
      single,
    );
  }

  late final _ml_single_closePtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ml_single_h)>>(
          'ml_single_close');
  late final _ml_single_close =
      _ml_single_closePtr.asFunction<int Function(ml_single_h)>();

  /// @brief Invokes the model with the given input data.
  /// @details Even if the model has flexible input data dimensions,
  /// input data frames of an instance of a model should share the same dimension.
  /// Note that this will wait for the result until the invoke process is done. If an application wants to change the time to wait for an output, set the timeout using ml_single_set_timeout().
  /// @since_tizen 5.5
  /// @param[in] single The model handle to be inferred.
  /// @param[in] input The input data to be inferred.
  /// @param[out] output The allocated output buffer. The caller is responsible for freeing the output buffer with ml_tensors_data_destroy().
  /// @return @c 0 on success. Otherwise a negative error value.
  /// @note If the data for the output buffer is allocated by the neural network framework (ML_NNFW_TYPE_CUSTOM_FILTER supports this),
  /// then this buffer will be freed when closing the @a single automatically by the neural network framework, and will not available for use later.
  /// It is recommended to copy the output buffer from @a output if it is required to use it after the @a single handle is closed.
  /// @retval #ML_ERROR_NONE Successful.
  /// @retval #ML_ERROR_NOT_SUPPORTED Not supported.
  /// @retval #ML_ERROR_INVALID_PARAMETER Fail. The parameter is invalid.
  /// @retval #ML_ERROR_STREAMS_PIPE Failed to push a buffer into source element.
  /// @retval #ML_ERROR_TIMED_OUT Failed to get the result from sink element.
  /// @retval #ML_ERROR_OUT_OF_MEMORY Failed to allocate required memory.
  int ml_single_invoke(
    ml_single_h single,
    ml_tensors_data_h input,
    ffi.Pointer<ml_tensors_data_h> output,
  ) {
    return _ml_single_invoke(
      single,
      input,
      output,
    );
  }

  late final _ml_single_invokePtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(ml_single_h, ml_tensors_data_h,
              ffi.Pointer<ml_tensors_data_h>)>>('ml_single_invoke');
  late final _ml_single_invoke = _ml_single_invokePtr.asFunction<
      int Function(
          ml_single_h, ml_tensors_data_h, ffi.Pointer<ml_tensors_data_h>)>();

  /// @brief Invokes the model with the given input data and fills the @a output data handle. This is generally faster than ml_single_invoke().
  /// @details The caller should preallocate memory buffers of the given output handle before calling the API.
  /// Note that ml_single_invoke() allocates memory buffers of the output handle in the API, which may incur memcpy.
  /// @since_tizen 6.5
  /// @param[in] single The model handle to be inferred.
  /// @param[in] input The input data to be inferred.
  /// @param[in,out] output The output data to be filled by the API. Output should be preallocated before calling the API.
  /// @return @c 0 on success. Otherwise a negative error value.
  /// @retval #ML_ERROR_NONE Successful.
  /// @retval #ML_ERROR_NOT_SUPPORTED Not supported.
  /// @retval #ML_ERROR_INVALID_PARAMETER Fail. The parameter is invalid.
  /// @retval #ML_ERROR_STREAMS_PIPE Failed to push a buffer into source element.
  /// @retval #ML_ERROR_TIMED_OUT Failed to get the result from sink element.
  /// @retval #ML_ERROR_OUT_OF_MEMORY Failed to allocate required memory.
  int ml_single_invoke_fast(
    ml_single_h single,
    ml_tensors_data_h input,
    ml_tensors_data_h output,
  ) {
    return _ml_single_invoke_fast(
      single,
      input,
      output,
    );
  }

  late final _ml_single_invoke_fastPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(ml_single_h, ml_tensors_data_h,
              ml_tensors_data_h)>>('ml_single_invoke_fast');
  late final _ml_single_invoke_fast = _ml_single_invoke_fastPtr.asFunction<
      int Function(ml_single_h, ml_tensors_data_h, ml_tensors_data_h)>();

  /// @brief Invokes the model with the given input data with the given tensors information.
  /// @details This function changes the input tensors information for the model, and returns the corresponding output data.
  /// A model/framework may not support changing the information.
  /// Note that this will wait for the result until the invoke process is done. If an application wants to change the time to wait for an output, set the timeout using ml_single_set_timeout().
  /// @since_tizen 6.0
  /// @param[in] single The model handle to be inferred.
  /// @param[in] input The input data to be inferred.
  /// @param[in] in_info The handle of input tensors information.
  /// @param[out] output The allocated output buffer. The caller is responsible for freeing the output buffer with ml_tensors_data_destroy().
  /// @param[out] out_info The handle of output tensors information. The caller is responsible for freeing the information with ml_tensors_info_destroy().
  /// @return @c 0 on success. Otherwise a negative error value.
  /// @retval #ML_ERROR_NONE Successful.
  /// @retval #ML_ERROR_NOT_SUPPORTED Not supported.
  /// @retval #ML_ERROR_INVALID_PARAMETER Fail. The parameter is invalid.
  /// @retval #ML_ERROR_STREAMS_PIPE Failed to push a buffer into source element.
  /// @retval #ML_ERROR_TIMED_OUT Failed to get the result from sink element.
  /// @retval #ML_ERROR_OUT_OF_MEMORY Failed to allocate required memory.
  int ml_single_invoke_dynamic(
    ml_single_h single,
    ml_tensors_data_h input,
    ml_tensors_info_h in_info,
    ffi.Pointer<ml_tensors_data_h> output,
    ffi.Pointer<ml_tensors_info_h> out_info,
  ) {
    return _ml_single_invoke_dynamic(
      single,
      input,
      in_info,
      output,
      out_info,
    );
  }

  late final _ml_single_invoke_dynamicPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(
              ml_single_h,
              ml_tensors_data_h,
              ml_tensors_info_h,
              ffi.Pointer<ml_tensors_data_h>,
              ffi.Pointer<ml_tensors_info_h>)>>('ml_single_invoke_dynamic');
  late final _ml_single_invoke_dynamic =
      _ml_single_invoke_dynamicPtr.asFunction<
          int Function(
              ml_single_h,
              ml_tensors_data_h,
              ml_tensors_info_h,
              ffi.Pointer<ml_tensors_data_h>,
              ffi.Pointer<ml_tensors_info_h>)>();

  /// @brief Gets the information (tensor dimension, type, name and so on) of required input data for the given model.
  /// @details Note that a model may not have such information if its input type is flexible.
  /// The names of tensors are sometimes unavailable (optional), while its dimensions and types are always available.
  /// @since_tizen 5.5
  /// @param[in] single The model handle.
  /// @param[out] info The handle of input tensors information. The caller is responsible for freeing the information with ml_tensors_info_destroy().
  /// @return @c 0 on success. Otherwise a negative error value.
  /// @retval #ML_ERROR_NONE Successful.
  /// @retval #ML_ERROR_NOT_SUPPORTED Not supported.
  /// @retval #ML_ERROR_INVALID_PARAMETER Fail. The parameter is invalid.
  int ml_single_get_input_info(
    ml_single_h single,
    ffi.Pointer<ml_tensors_info_h> info,
  ) {
    return _ml_single_get_input_info(
      single,
      info,
    );
  }

  late final _ml_single_get_input_infoPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(ml_single_h,
              ffi.Pointer<ml_tensors_info_h>)>>('ml_single_get_input_info');
  late final _ml_single_get_input_info = _ml_single_get_input_infoPtr
      .asFunction<int Function(ml_single_h, ffi.Pointer<ml_tensors_info_h>)>();

  /// @brief Gets the information (tensor dimension, type, name and so on) of output data for the given model.
  /// @details Note that a model may not have such information if its output type is flexible and output type is not determined statically.
  /// The names of tensors are sometimes unavailable (optional), while its dimensions and types are always available.
  /// @since_tizen 5.5
  /// @param[in] single The model handle.
  /// @param[out] info The handle of output tensors information. The caller is responsible for freeing the information with ml_tensors_info_destroy().
  /// @return @c 0 on success. Otherwise a negative error value.
  /// @retval #ML_ERROR_NONE Successful.
  /// @retval #ML_ERROR_NOT_SUPPORTED Not supported.
  /// @retval #ML_ERROR_INVALID_PARAMETER Fail. The parameter is invalid.
  int ml_single_get_output_info(
    ml_single_h single,
    ffi.Pointer<ml_tensors_info_h> info,
  ) {
    return _ml_single_get_output_info(
      single,
      info,
    );
  }

  late final _ml_single_get_output_infoPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(ml_single_h,
              ffi.Pointer<ml_tensors_info_h>)>>('ml_single_get_output_info');
  late final _ml_single_get_output_info = _ml_single_get_output_infoPtr
      .asFunction<int Function(ml_single_h, ffi.Pointer<ml_tensors_info_h>)>();

  /// @brief Sets the information (tensor dimension, type, name and so on) of required input data for the given model.
  /// @details Note that a model/framework may not support changing the information.
  /// Use ml_single_get_input_info() and ml_single_get_output_info() instead for this framework.
  /// @since_tizen 6.0
  /// @param[in] single The model handle.
  /// @param[in] info The handle of input tensors information.
  /// @return @c 0 on success. Otherwise a negative error value.
  /// @retval #ML_ERROR_NONE Successful.
  /// @retval #ML_ERROR_NOT_SUPPORTED Not supported.
  /// @retval #ML_ERROR_INVALID_PARAMETER Fail. The parameter is invalid.
  int ml_single_set_input_info(
    ml_single_h single,
    ml_tensors_info_h info,
  ) {
    return _ml_single_set_input_info(
      single,
      info,
    );
  }

  late final _ml_single_set_input_infoPtr = _lookup<
          ffi.NativeFunction<ffi.Int Function(ml_single_h, ml_tensors_info_h)>>(
      'ml_single_set_input_info');
  late final _ml_single_set_input_info = _ml_single_set_input_infoPtr
      .asFunction<int Function(ml_single_h, ml_tensors_info_h)>();

  /// @brief Sets the maximum amount of time to wait for an output, in milliseconds.
  /// @since_tizen 5.5
  /// @param[in] single The model handle.
  /// @param[in] timeout The time to wait for an output.
  /// @return @c 0 on success. Otherwise a negative error value.
  /// @retval #ML_ERROR_NONE Successful.
  /// @retval #ML_ERROR_NOT_SUPPORTED Not supported.
  /// @retval #ML_ERROR_INVALID_PARAMETER Fail. The parameter is invalid.
  int ml_single_set_timeout(
    ml_single_h single,
    int timeout,
  ) {
    return _ml_single_set_timeout(
      single,
      timeout,
    );
  }

  late final _ml_single_set_timeoutPtr = _lookup<
          ffi.NativeFunction<ffi.Int Function(ml_single_h, ffi.UnsignedInt)>>(
      'ml_single_set_timeout');
  late final _ml_single_set_timeout =
      _ml_single_set_timeoutPtr.asFunction<int Function(ml_single_h, int)>();

  /// @brief Sets the property value for the given model.
  /// @details Note that a model/framework may not support changing the property after opening the model.
  /// @since_tizen 6.0
  /// @param[in] single The model handle.
  /// @param[in] name The property name.
  /// @param[in] value The property value.
  /// @return @c 0 on success. Otherwise a negative error value.
  /// @retval #ML_ERROR_NONE Successful.
  /// @retval #ML_ERROR_NOT_SUPPORTED Not supported.
  /// @retval #ML_ERROR_INVALID_PARAMETER Fail. The parameter is invalid.
  int ml_single_set_property(
    ml_single_h single,
    ffi.Pointer<ffi.Char> name,
    ffi.Pointer<ffi.Char> value,
  ) {
    return _ml_single_set_property(
      single,
      name,
      value,
    );
  }

  late final _ml_single_set_propertyPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(ml_single_h, ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>)>>('ml_single_set_property');
  late final _ml_single_set_property = _ml_single_set_propertyPtr.asFunction<
      int Function(
          ml_single_h, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)>();

  /// @brief Gets the property value for the given model.
  /// @since_tizen 6.0
  /// @param[in] single The model handle.
  /// @param[in] name The property name.
  /// @param[out] value The property value. The caller is responsible for freeing the value using g_free().
  /// @return @c 0 on success. Otherwise a negative error value.
  /// @retval #ML_ERROR_NONE Successful.
  /// @retval #ML_ERROR_NOT_SUPPORTED Not supported.
  /// @retval #ML_ERROR_INVALID_PARAMETER Fail. The parameter is invalid.
  int ml_single_get_property(
    ml_single_h single,
    ffi.Pointer<ffi.Char> name,
    ffi.Pointer<ffi.Pointer<ffi.Char>> value,
  ) {
    return _ml_single_get_property(
      single,
      name,
      value,
    );
  }

  late final _ml_single_get_propertyPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(ml_single_h, ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Pointer<ffi.Char>>)>>('ml_single_get_property');
  late final _ml_single_get_property = _ml_single_get_propertyPtr.asFunction<
      int Function(ml_single_h, ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Pointer<ffi.Char>>)>();

  /// @brief Makes a single instance with given ml-option.
  /// @since_tizen 7.0
  /// @remarks %http://tizen.org/privilege/mediastorage is needed if @a option is relevant to media storage.
  /// @remarks %http://tizen.org/privilege/externalstorage is needed if @a option is relevant to external storage.
  /// @param[out] single This is the model handle opened. Users are required to close
  /// the given instance with ml_single_close().
  /// @param[in] option The handle of ml-option.
  /// @return @c 0 on success. Otherwise a negative error value.
  /// @retval #ML_ERROR_NONE Successful.
  /// @retval #ML_ERROR_NOT_SUPPORTED Not supported.
  /// @retval #ML_ERROR_PERMISSION_DENIED The application does not have the privilege to access to the media storage or external storage.
  /// @retval #ML_ERROR_INVALID_PARAMETER Fail. The parameter is invalid.
  /// @retval #ML_ERROR_STREAMS_PIPE Failed to start the pipeline.
  /// @retval #ML_ERROR_OUT_OF_MEMORY Failed to allocate required memory.
  int ml_single_open_with_option(
    ffi.Pointer<ml_single_h> single,
    ml_option_h option,
  ) {
    return _ml_single_open_with_option(
      single,
      option,
    );
  }

  late final _ml_single_open_with_optionPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<ml_single_h>,
              ml_option_h)>>('ml_single_open_with_option');
  late final _ml_single_open_with_option = _ml_single_open_with_optionPtr
      .asFunction<int Function(ffi.Pointer<ml_single_h>, ml_option_h)>();
}

/// @brief A handle of a single-shot instance.
/// @since_tizen 5.5
typedef ml_single_h = ffi.Pointer<ffi.Void>;

/// @brief A handle of a tensors metadata instance.
/// @since_tizen 5.5
typedef ml_tensors_info_h = ffi.Pointer<ffi.Void>;

/// @brief Types of NNFWs.
/// @details To check if a nnfw-type is supported in a system, an application may call the API, ml_check_nnfw_availability().
/// @since_tizen 5.5
abstract class ml_nnfw_type_e {
  /// < NNFW is not specified (Try to determine the NNFW with file extension).
  static const int ML_NNFW_TYPE_ANY = 0;

  /// < Custom filter (Independent shared object).
  static const int ML_NNFW_TYPE_CUSTOM_FILTER = 1;

  /// < Tensorflow-lite (.tflite).
  static const int ML_NNFW_TYPE_TENSORFLOW_LITE = 2;

  /// < Tensorflow (.pb).
  static const int ML_NNFW_TYPE_TENSORFLOW = 3;

  /// < Neural Network Inference framework, which is developed by SR (Samsung Research).
  static const int ML_NNFW_TYPE_NNFW = 4;

  /// < Intel Movidius Neural Compute SDK (libmvnc). (Since 6.0)
  static const int ML_NNFW_TYPE_MVNC = 5;

  /// < Intel OpenVINO. (Since 6.0)
  static const int ML_NNFW_TYPE_OPENVINO = 6;

  /// < VeriSilicon's Vivante. (Since 6.0)
  static const int ML_NNFW_TYPE_VIVANTE = 7;

  /// < Google Coral Edge TPU (USB). (Since 6.0)
  static const int ML_NNFW_TYPE_EDGE_TPU = 8;

  /// < Arm Neural Network framework (support for caffe and tensorflow-lite). (Since 6.0)
  static const int ML_NNFW_TYPE_ARMNN = 9;

  /// < Qualcomm SNPE (Snapdragon Neural Processing Engine (.dlc). (Since 6.0)
  static const int ML_NNFW_TYPE_SNPE = 10;

  /// < PyTorch (.pt). (Since 6.5)
  static const int ML_NNFW_TYPE_PYTORCH = 11;

  /// < Inference supported from NNTrainer, SR On-device Training Framework (Since 6.5)
  static const int ML_NNFW_TYPE_NNTR_INF = 12;

  /// < Inference framework for Samsung Tizen TV (Since 6.5)
  static const int ML_NNFW_TYPE_VD_AIFW = 13;

  /// < TRIxENGINE accesses TRIV/TRIA NPU low-level drivers directly (.tvn). (Since 6.5) You may need to use high-level drivers wrapping this low-level driver in some devices: e.g., AIFW
  static const int ML_NNFW_TYPE_TRIX_ENGINE = 14;

  /// < Apache MXNet (Since 7.0)
  static const int ML_NNFW_TYPE_MXNET = 15;

  /// < Apache TVM (Since 7.0)
  static const int ML_NNFW_TYPE_TVM = 16;

  /// < SNAP (Samsung Neural Acceleration Platform), only for Android. (Since 6.0)
  static const int ML_NNFW_TYPE_SNAP = 8193;
}

/// @brief Types of hardware resources to be used for NNFWs. Note that if the affinity (nnn) is not supported by the driver or hardware, it is ignored.
/// @since_tizen 5.5
abstract class ml_nnfw_hw_e {
  /// < Hardware resource is not specified.
  static const int ML_NNFW_HW_ANY = 0;

  /// < Try to schedule and optimize if possible.
  static const int ML_NNFW_HW_AUTO = 1;

  /// < 0x1000: any CPU. 0x1nnn: CPU # nnn-1.
  static const int ML_NNFW_HW_CPU = 4096;

  /// < 0x1100: SIMD in CPU. (Since 6.0)
  static const int ML_NNFW_HW_CPU_SIMD = 4352;

  /// < 0x1100: NEON (alias for SIMD) in CPU. (Since 6.0)
  static const int ML_NNFW_HW_CPU_NEON = 4352;

  /// < 0x2000: any GPU. 0x2nnn: GPU # nnn-1.
  static const int ML_NNFW_HW_GPU = 8192;

  /// < 0x3000: any NPU. 0x3nnn: NPU # nnn-1.
  static const int ML_NNFW_HW_NPU = 12288;

  /// < 0x3001: Intel Movidius Stick. (Since 6.0)
  static const int ML_NNFW_HW_NPU_MOVIDIUS = 12289;

  /// < 0x3002: Google Coral Edge TPU (USB). (Since 6.0)
  static const int ML_NNFW_HW_NPU_EDGE_TPU = 12290;

  /// < 0x3003: VeriSilicon's Vivante. (Since 6.0)
  static const int ML_NNFW_HW_NPU_VIVANTE = 12291;

  /// < 0x3004: Samsung S.LSI. (Since 6.5)
  static const int ML_NNFW_HW_NPU_SLSI = 12292;

  /// < 0x13000: any SR (Samsung Research) made NPU. (Since 6.0)
  static const int ML_NNFW_HW_NPU_SR = 77824;
}

/// @brief A handle of input or output frames. #ml_tensors_info_h is the handle for tensors metadata.
/// @since_tizen 5.5
typedef ml_tensors_data_h = ffi.Pointer<ffi.Void>;

/// @brief A handle of a ml-option instance.
/// @since_tizen 7.0
typedef ml_option_h = ffi.Pointer<ffi.Void>;
