// Copyright 2021 Samsung Electronics Co., Ltd. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// ignore_for_file: type=lint, unused_element, unused_field

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
import 'dart:ffi' as ffi;

/// Dart bindings for Tizen mv-roi-tracker APIs.
class Tizen70MvRoiTracker {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  Tizen70MvRoiTracker(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  Tizen70MvRoiTracker.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  /// @brief Creates tracker handle.
  /// @details Use this function to create a tracker handle.
  ///
  /// @since_tizen 7.0
  ///
  /// @remarks The @a handle should be released using mv_roi_tracker_destroy().
  ///
  /// @param[out] handle   The handle to the tracker to be created
  ///
  /// @return @c 0 on success, otherwise a negative error value
  /// @retval #MEDIA_VISION_ERROR_NONE Successful
  /// @retval #MEDIA_VISION_ERROR_NOT_SUPPORTED Not supported
  /// @retval #MEDIA_VISION_ERROR_INVALID_PARAMETER Invalid parameter
  /// @retval #MEDIA_VISION_ERROR_OUT_OF_MEMORY Out of memory
  ///
  /// @see mv_roi_tracker_destroy()
  int mv_roi_tracker_create(
    ffi.Pointer<mv_roi_tracker_h> handle,
  ) {
    return _mv_roi_tracker_create(
      handle,
    );
  }

  late final _mv_roi_tracker_createPtr = _lookup<
          ffi.NativeFunction<ffi.Int Function(ffi.Pointer<mv_roi_tracker_h>)>>(
      'mv_roi_tracker_create');
  late final _mv_roi_tracker_create = _mv_roi_tracker_createPtr
      .asFunction<int Function(ffi.Pointer<mv_roi_tracker_h>)>();

  /// @brief Destroys tracker handle and release all its resources.
  ///
  /// @since_tizen 7.0
  ///
  /// @param[in] handle    The handle to the tracker object to be destroyed
  ///
  /// @return @c 0 on success, otherwise a negative error value
  /// @retval #MEDIA_VISION_ERROR_NONE Successful
  /// @retval #MEDIA_VISION_ERROR_INVALID_PARAMETER Invalid parameter
  ///
  /// @pre Create tracker handle by using mv_roi_tracker_create()
  int mv_roi_tracker_destroy(
    mv_roi_tracker_h handle,
  ) {
    return _mv_roi_tracker_destroy(
      handle,
    );
  }

  late final _mv_roi_tracker_destroyPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(mv_roi_tracker_h)>>(
          'mv_roi_tracker_destroy');
  late final _mv_roi_tracker_destroy =
      _mv_roi_tracker_destroyPtr.asFunction<int Function(mv_roi_tracker_h)>();

  /// @brief Configures the attributes of the roi tracker.
  /// @details Use this function to configure the attributes of the roi tracker
  /// which is set to @a engine_config.
  ///
  /// @since_tizen 7.0
  ///
  /// @param[in] handle         The handle to the roi tracker
  /// @param[in] engine_config The handle to the configuration of
  /// engine.
  ///
  /// @return @c 0 on success, otherwise a negative error value
  /// @retval #MEDIA_VISION_ERROR_NONE Successful
  /// @retval #MEDIA_VISION_ERROR_NOT_SUPPORTED Not supported
  /// @retval #MEDIA_VISION_ERROR_INVALID_PARAMETER Invalid parameter
  /// in @a engine_config
  int mv_roi_tracker_configure(
    mv_roi_tracker_h handle,
    mv_engine_config_h engine_config,
  ) {
    return _mv_roi_tracker_configure(
      handle,
      engine_config,
    );
  }

  late final _mv_roi_tracker_configurePtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(mv_roi_tracker_h,
              mv_engine_config_h)>>('mv_roi_tracker_configure');
  late final _mv_roi_tracker_configure = _mv_roi_tracker_configurePtr
      .asFunction<int Function(mv_roi_tracker_h, mv_engine_config_h)>();

  /// @brief Prepares roi tracker.
  /// @details Use this function to prepare roi tracker based on
  /// the configurtion. ROI related variables are used when 'mv_roi_tracker_perform' is executed.
  ///
  /// @since_tizen 7.0
  ///
  /// @param[in] handle    The handle to the roi tracker
  /// @param[in] x         The x coordinate to set ROI to be tracked
  /// @param[in] y         The y coordinate to set ROI to be tracked
  /// @param[in] width     The width to set ROI to be tracked
  /// @param[in] height    The height to set ROI to be tracked
  /// @return @c 0 on success, otherwise a negative error value
  /// @retval #MEDIA_VISION_ERROR_NONE Successful
  /// @retval #MEDIA_VISION_ERROR_NOT_SUPPORTED Not supported
  /// @retval #MEDIA_VISION_ERROR_INVALID_PARAMETER Invalid parameter
  int mv_roi_tracker_prepare(
    mv_roi_tracker_h handle,
    int x,
    int y,
    int width,
    int height,
  ) {
    return _mv_roi_tracker_prepare(
      handle,
      x,
      y,
      width,
      height,
    );
  }

  late final _mv_roi_tracker_preparePtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(mv_roi_tracker_h, ffi.Int, ffi.Int, ffi.Int,
              ffi.Int)>>('mv_roi_tracker_prepare');
  late final _mv_roi_tracker_prepare = _mv_roi_tracker_preparePtr
      .asFunction<int Function(mv_roi_tracker_h, int, int, int, int)>();

  /// @brief Tracks with a given tracker on the @a source.
  /// @details Use this function to track with a given source and ROI information which is set to 'mv_roi_tracker_prepare'.
  /// This function returns a proper ROI coordinates of the tracked region inside given source.
  ///
  /// @since_tizen 7.0
  ///
  /// @param[in]  handle     The handle to the tracker object.
  /// @param[in]  source     The handle to the source of the media.
  /// @param[in]  tracked_cb The callback which will receive the tracked results.
  /// @param[in]  user_data  The user data passed from the code where
  /// mv_roi_tracker_perform() is invoked.
  /// This data will be accessible in @a tracked_cb callback.
  /// @return @c 0 on success, otherwise a negative error value
  /// @retval #MEDIA_VISION_ERROR_NONE Successful
  /// @retval #MEDIA_VISION_ERROR_NOT_SUPPORTED Not supported
  /// @retval #MEDIA_VISION_ERROR_INVALID_PARAMETER Invalid parameter
  /// @retval #MEDIA_VISION_ERROR_OUT_OF_MEMORY Out of memory
  /// @retval #MEDIA_VISION_ERROR_INVALID_OPERATION Invalid operation
  /// @retval #MEDIA_VISION_ERROR_NOT_SUPPORTED_FORMAT Source colorspace
  /// isn't supported
  ///
  /// @pre Create a new tracker handle by calling @ref mv_roi_tracker_create()
  int mv_roi_tracker_perform(
    mv_roi_tracker_h handle,
    mv_source_h source,
    mv_roi_tracker_tracked_cb tracked_cb,
    ffi.Pointer<ffi.Void> user_data,
  ) {
    return _mv_roi_tracker_perform(
      handle,
      source,
      tracked_cb,
      user_data,
    );
  }

  late final _mv_roi_tracker_performPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(
              mv_roi_tracker_h,
              mv_source_h,
              mv_roi_tracker_tracked_cb,
              ffi.Pointer<ffi.Void>)>>('mv_roi_tracker_perform');
  late final _mv_roi_tracker_perform = _mv_roi_tracker_performPtr.asFunction<
      int Function(mv_roi_tracker_h, mv_source_h, mv_roi_tracker_tracked_cb,
          ffi.Pointer<ffi.Void>)>();
}

/// @brief The ROI tracker handle.
/// @since_tizen 7.0
typedef mv_roi_tracker_h = ffi.Pointer<ffi.Void>;

/// @brief The handle to the Media Vision API engine algorithms configuration.
/// @details Configuration is a dictionary consists of key and value pairs to
/// collect engine-specific settings and allow Media Vision module to
/// access them internally. Engine configuration provides developer by
/// the possibility to make computer vision algorithms work better
/// in particular conditions of API usage. To create engine
/// configuration handle mv_create_engine_config() function has to
/// be used. When configuration is not needed any more, it is required to
/// destroy it and release resources by mv_destroy_engine_config()
/// function.
///
/// @since_tizen @if MOBILE 2.4 @else 3.0 @endif
///
/// @see mv_create_engine_config()
/// @see mv_destroy_engine_config()
typedef mv_engine_config_h = ffi.Pointer<ffi.Void>;

/// @brief The handle to the source.
///
/// @since_tizen @if MOBILE 2.4 @else 3.0 @endif
typedef mv_source_h = ffi.Pointer<ffi.Void>;

/// @brief Called when roi in @a source are detected.
/// @details This type callback is invoked each time when
/// mv_roi_tracker_perform() is called to provide
/// the results of the tracked roi.
///
/// @since_tizen 7.0
/// @remarks The @a roi should not be released by app. They can be used only in the callback.
///
/// @param[in] source     The handle to the source of the media where
/// roi tracker were performed. @a source is the same object
/// for which mv_roi_tracker_perform() was called.
/// It should be released by calling mv_destroy_source()
/// when it's not needed anymore.
/// @param[in] roi        Roi of the tracked result.
/// @param[in] user_data  The user data passed from callback invoking code
///
/// @see mv_roi_tracker_perform()
typedef mv_roi_tracker_tracked_cb
    = ffi.Pointer<ffi.NativeFunction<mv_roi_tracker_tracked_cbFunction>>;
typedef mv_roi_tracker_tracked_cbFunction = ffi.Void Function(
    mv_source_h source, mv_rectangle_s roi, ffi.Pointer<ffi.Void> user_data);
typedef Dartmv_roi_tracker_tracked_cbFunction = void Function(
    mv_source_h source, mv_rectangle_s roi, ffi.Pointer<ffi.Void> user_data);

/// @brief Location of the object bounded by rectangle defined by
/// coordinates of top left corner, width and height.
///
/// @since_tizen @if MOBILE 2.4 @else 3.0 @endif
final class mv_rectangle_s extends ffi.Struct {
  /// < Top left corner of rectangle coordinates
  external mv_point_s point;

  /// < Width of the bounding rectangle
  @ffi.Int()
  external int width;

  /// < Height of the bounding rectangle
  @ffi.Int()
  external int height;
}

/// @brief Point in 2D space.
///
/// @since_tizen @if MOBILE 2.4 @else 3.0 @endif
final class mv_point_s extends ffi.Struct {
  /// < X-axis coordinate of the point in 2D space
  @ffi.Int()
  external int x;

  /// < Y-axis coordinate of the point in 2D space
  @ffi.Int()
  external int y;
}

const String MV_ROI_TRACKER_TYPE = 'MV_ROI_TRACKER_TYPE';
