preamble: |
  // Copyright 2021 Samsung Electronics Co., Ltd. All rights reserved.
  // Use of this source code is governed by a BSD-style license that can be
  // found in the LICENSE file.
  // ignore_for_file: type=lint, unused_element, unused_field

name: Tizen70CapiLocationManager
description: Dart bindings for Tizen capi-location-manager APIs.
output: ../../lib/src/bindings/7.0/generated_bindings_capi_location_manager.dart
llvm-path:
- /usr/lib/llvm-12
headers:
  entry-points:
  - entrypoints-capi-location-manager.h
  include-directives:
  - '**/locations.h'
  - '**/location_bounds.h'
compiler-opts:
- -m32
- -Wno-incomplete-setjmp-declaration
- -I./rootstraps/7.0/usr/include/
- -I./rootstraps/7.0/usr/include/location/
enums:
  rename:
    _+(.*): $1
